### ISSUE TITLE
Shading in Pulsar jars

### ISSUE THREAD

**Issue by sschepens** [apache/incubator-pulsar#1001]
Pulsar jars published to maven are shading dependencies and this causes some issues, like inability to share an EventLoopGroup created with an unshaded Netty version with PulsarClient which expects a shaded Netty version.
This wasn't the case on previous versions.

Shading should be OK when generating uber jars for thinks like brokers and etc, but not for libraries ment to be imported like pulsar-client, pulsar-common, etc.

**Comment by sschepens** [comment]
I just found #846 
I don't think this is right though, I don't remember the last time I imported a library that was shaded.
And dependency conflicts is something every Java developer should be familiar with

**Comment by merlimat** [comment]
@sschepens We had many issues with people having conflicts with different protobuf or netty versions and taking long time to debug those at runtime. 

I think shading by default is "nicer" to users. There is still the options to get unshaded client artifact by using `pulsar-client-original`. Do you think the option should be specified more prominently in the client documentation?

> I don't remember the last time I imported a library that was shaded.

Many libraries are actually doing that under the hood (eg: Netty, JCommander and many others).

**Comment by sijie** [comment]
Now pulsar have many shading jars:

- pulsar-client-shade
- pulsar-client-admin-shade
- pulsar-broker-shade
