### ISSUE TITLE
Rename global zookeeper cluster to configuration/replication-configuration cluster

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1014]
The global zookeeper cluster is mostly used for storing replication related configuration. It is a bit confusing to new users what does global zookeeper means and people are worried that global zookeeper is a bottleneck of the availability of pulsar.

It would be good to rename global zookeeper to configuration or replication-configuration cluster.

The changes should include:

- documentation
- shell command (e.g. --global-zookeeper)
- code if there are things needed to be changed.

**Comment by zhaijack** [comment]
@merlimat @sijie , for the new config, which name do you like, "replication-configuration", "--configuration-zookeeper" or "geo-configuration-zookeeper"

**Comment by rdhabalia** [comment]
Actually global-zookeeper is not only used to store replication/geo metadata but it also stores various namespace and admin policies. So, I think we should not rename it to something specific for replication.
Isn't `global-zookeeper` is acceptable name as it's being shared by different clusters?

**Comment by zhaijack** [comment]
As @sijie mentioned, there may be some mis-leading for new user.

**Comment by sijie** [comment]
@rdhabalia we learned from our customers that 'global-zookeeper' is a bit confusing. people feels that the global zookeeper is the single point of failure, when it is down, pulsar is not functionable. since it is mostly used for configuration/policies, it is better to rename it to make the meaning more clear, so people will know directly that it is used for storing configurations/policies and they will not be freak out, or having other bad impressions.

I was thinking of `configuration-zookeeper`, because policies are sort of "configuration"s.

**Comment by merlimat** [comment]
I would suggest `configuration-store`, then we can think how to present that it's actually implemented with zookeeper.

**Comment by zhaijack** [comment]
Thanks @merlimat,  will wait for 1 day, and if there is no objection for name `configuration-store`, will do the change in the code, and send a new PR.
@sijie @rdhabalia for the new name `configuration-store`.

**Comment by sijie** [comment]
+1 on `configuration-store`

**Comment by zhaijack** [comment]
https://github.com/apache/incubator-pulsar/pull/1059 is for the fix. 
@merlimat Since the PR is marked as 2.0, does  this mean the PR should wait after 1.22 released?

**Comment by sijie** [comment]
This is implemented by #1059
