### ISSUE TITLE
Hashcode of message key is inconsistent between different language clients

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1017]
#### Expected behavior

Hashcode of message key should be consistent between different language clients. Otherwise two messages of same message key might have different hash codes using different language clients (e.g. java vs cpp).

#### Actual behavior

Based on my understand of pulsar code, the message key is calculated using `String.hashCode()` using java client, while `boost::hash` is used for calculating the hash code when using cpp client.

**Comment by sijie** [comment]
This is a question raised up based on looking into the code. We need to verify if we have any tricks on cpp client. /cc @merlimat

**Comment by Licht-T** [comment]
`String.hashCode()` uses the simple hash. On the other side, `boost::hash` uses MurmurHash3. IMO, we have to use widely-used and good hash like MurmurHash in each language client.
https://docs.oracle.com/javase/7/docs/api/java/lang/String.html

**Comment by merlimat** [comment]
The biggest problem is how to upgrade the default hashing scheme. New applications can easily use different hashing, but who's using the current client and relies on hashing cannot just switch to a new scheme.

**Comment by sijie** [comment]
@Licht-T @merlimat 

I think the easiest way is to create a separate message router that uses MurmurHash3. Ask applications to use this new message router.
