### ISSUE TITLE
Pulsar standalone crashes with Assertion Failure

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1049]
#### Expected behavior

run `bin/pulsar standalone`, produce messages, kill pulsar standalone, and restart standalone again. The standalone is expected to run correctly.

#### Actual behavior

The standalone is crashed with `Assertion failed: (filter->size() > 0), function GetFilter, file table/block_based_table_reader.cc, line 1235.`

#### Steps to reproduce

as stated at `Expected behavior` section.

#### System configuration
**Pulsar version**: 1.21.0

**Comment by sijie** [comment]
The zipped data directory can be found here: https://drive.google.com/file/d/1jo7O41mQ9Elcs581jzYiS9dNla4csdab/view?usp=sharing

**Comment by sijie** [comment]
A rocksdb issue was reported at facebook/rocksdb#2717

**Comment by erenavsarogullari** [comment]
As a **workaround** (for testing-purpose): 
Remove previous `/data` folder (will be created again automatically) and run `bin/pulsar standalone` again.

**Pulsar version:** 1.22.0
