### ISSUE TITLE
Provide a mechanism to tell whether a consumer is the leader of a failover subscription

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1058]
`Failover` subscription is sort of providing a `leader-election` mechanism over multiple consumers within a failover subscription. It would be good to provide a mechanism to expose state changes (e.g. become leader, become standay) to the consumer, so applications can use this information to determine if a consumer is the leader consumer or not.

**Comment by jerrypeng** [comment]
+1

**Comment by sijie** [comment]
I am starting looking at this one (just in case on other people is working on it).
