### ISSUE TITLE
Support pluggable authorization mechansim

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1072]
Currently pulsar only supports pluggable authentication mechanisms. It doesn't support pluggable authorization provides. It would be good to make this also pluggable, so users can easily integrate with their own authorization infrastructures.

**Comment by rdhabalia** [comment]
We have also seen this requirement when user wants to deploy proxy and websocket-proxy by themselves and they want to implement auth&auth which requires pluggable authorization. If it's fine then I can take it up and will create a PR.??

**Comment by merlimat** [comment]
Yep, go for it

**Comment by merlimat** [comment]
I had it marked to 2.0, but if you think you can do that for 1.22, the better

**Comment by sijie** [comment]
This is fixed by #1200
