### ISSUE TITLE
Add  pulsar-prometheus docker image to pulsar repo

### ISSUE THREAD

**Issue by rdhabalia** [apache/incubator-pulsar#1119]
#### Expected behavior

We have added [pulsar-prometheus](https://github.com/apache/incubator-pulsar/blob/master/deployment/dcos/PulsarGroups.json#L251) docker image in #950 which is not present into pulsar repo. It would be great if we can add it to pulsar repo for any future changes or enhancement.

**Comment by zhaijack** [comment]
+1. Thanks for the reminder @rdhabalia .

**Comment by sijie** [comment]
This is fixed by #1127

**Comment by sijie** [comment]
This fix is contributed by @zhaijack
