### ISSUE TITLE
Change default pulsar stanalone behavior

### ISSUE THREAD

**Issue by aahmed-se** [apache/incubator-pulsar#1152]
Currently pulsar in standalone mode expects an advertised address to be passed to use localhost this is unnecessarily complicated , for cases such as docker images it's even more complicated in say osx environments where docker runs inside a linux vm.

Suggestion is to enable default pulsar proxy type configuration for standalone mode so it becomes easier to use.

**Comment by merlimat** [comment]
We should make the Standalone service to behave like the Proxy.

Currently, the Pulsar standalone service is a very regular Pulsar deployment, with 1 broker / 1 bookie / 1 ZK all running in the same JVM. 

The normal lookup and redirection for service discovery applies to standalone. 

If the "hostname" of the machine where the Standalone service is running is not set, or set to a name that is not in DNS or anyway reachable from other machines, the client will fail. 

The user can specify `--advertised-address 1.2.3.4` but that sometimes is difficult to diagnose, and it other cases (like dynamic container envs) difficult to set.

If we make the Standalone to force the "proxy" flag in the `Connected` response, it will make all clients to always connect through the same address they used for the initial connection, removing the need to fix the broker advertised address.

**Comment by EronWright** [comment]
I wonder if an alternative fix would have been to force the proxy flag when no advertised address is configured.  This would improve support for advanced configurations in standalone mode.

**Comment by merlimat** [comment]
That would pose a problem in a typical bare-metal deployment where the `advertisedAddress` is left empty and it's derived from hostname, but you still don't want to act like a proxy, for efficiency reasons

**Comment by EronWright** [comment]
Good point.

Here's another possibility, force the proxy flag when in standalone mode and the advertised address is `localhost`.  This would allow standalone mode to support advertised listeners.  I observe that `PulsarStandaloneStarter` does the following:

https://github.com/apache/pulsar/blob/5ad405988fabb4b28dbdbd5aa5c9a10802f39af1/pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandaloneStarter.java#L78-L80
