### ISSUE TITLE
Pulsar proxy should forward HTTP requests to brokers

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#1206]
In order to be able to use admin API through proxy, the proxy needs to do reverse proxy to the broker, internally following redirects and writing result back to client.

**Comment by mgodave** [comment]
I'm taking a stab at this. Please assign to me.

**Comment by sijie** [comment]
@mgodave I don't think I can't assign to you. let's just use comments here to inform that you are taking this issue.

**Comment by mgodave** [comment]
okie dokie
