### ISSUE TITLE
Documentation required for Pulsar Proxy and TLS changes

### ISSUE THREAD

**Issue by jai1** [apache/incubator-pulsar#1229]
Need to add documentation for the flags added during Pulsar Proxy changes and TLS changes:-

https://github.com/apache/incubator-pulsar/pull/1225
#1208 
#1169 
#1168 
#1002

**Comment by sijie** [comment]
@jai1 are you working on this?

**Comment by ivankelly** [comment]
Broke this down into more digestible issues:

#1225 -> #2402 
#1208 -> #2403 
#1169 -> #2404 
#1168 -> Already there in http://pulsar.apache.org/docs/en/security-authorization/#proxy-roles
#1002 -> #2405
