### ISSUE TITLE
Provide documentation for running BookKeeper auto-recovery

### ISSUE THREAD

**Issue by lucperkins** [apache/incubator-pulsar#1288]
While BookKeeper auto-recovery has already been incorporated into the Pulsar setup for DC/OS and Kubernetes. We need to provide instructions for bare metal deployments as well.

**Comment by merlimat** [comment]
For auto-recovery, the main documentation is already in the BK side: http://bookkeeper.apache.org/docs/latest/admin/autorecovery/ 

We just need to mention, in our bare metal documentation, that auto-recovery can be either run as a separate component, or by enabling a flag to run the replication worker along with the bookies.

**Comment by lucperkins** [comment]
@merlimat Yep! Should be pretty easy 👍

**Comment by corewhq** [comment]
easy too!

**Comment by sijie** [comment]
@lucperkins are you working on this?
