### ISSUE TITLE
[Feature Proposal] client supporting JDK7

### ISSUE THREAD

**Issue by DongbinNie** [apache/incubator-pulsar#132]
Client supporting JDK7

[merlimat]
That would be very tricky. The current Java API itself is built upon JDK8 features like CompletableFuture. 
That would mean to do a rewrite of the client library to support JDK 7, but since it was EOLd ~2 years ago, I don't think it would be worth the effort.

As Andrew said above, WebSocket is probably a much easier/quicker way to solve that .

[DongbinNie]
While JDK7 is end of public updates from April 2015, JDK7 is still used widely, 45% in Plumber's report https://plumbr.eu/blog/java/java-version-and-vendor-data-analyzed-2016-edition
It will be helpful for Pulsar's adoption if the client supporting JDK7. Though WebSocket is a solution, but developers always prefer the first-class client.

**Comment by ivankelly** [comment]
There's far too much java8 usage to ever go to JDK7, so closing this as a won't fix.
