### ISSUE TITLE
Unable to delete partitioned metadata for a partitioned topic

### ISSUE THREAD

**Issue by cckellogg** [apache/incubator-pulsar#1383]
Unable to delete the metadata for a partitioned topic if no messages are produced on that topic.

Repo steps:

1 - create a partitioned topic
2 - delete the partitioned topic before producing messages to it

**Comment by jiazhai** [comment]
@cckellogg. Seems this is function as designed.

Added a Test case for this 
```
    public void testIssue1383() throws Exception {
        String key = "testIssue1383";
        final String subscriptionName = "my-ex-subscription-" + key;

        final String topicName = "persistent://prop/use/ns-abc2/topic-" + key;

        admin.tenants().createTenant("prop", new TenantInfo());
        admin.topics().createPartitionedTopic(topicName, 2);

        // 2. Create consumer
        try {
            pulsarClient.newConsumer()
                .topic(topicName)
                .subscriptionName(subscriptionName)
                .subscriptionType(SubscriptionType.Shared)
                .ackTimeout(ackTimeOutMillis, TimeUnit.MILLISECONDS)
                .subscribe();

            admin.topics().deletePartitionedTopic(topicName, true);   < ===
        } catch (Exception e) {
            log.error("Exception ", e);
        }
    }
```

In the line `< ===`, while using   `admin.topics().deletePartitionedTopic(topicName)`,   It will report:
```
org.apache.pulsar.client.admin.PulsarAdminException$PreconditionFailedException: Topic has active producers/subscriptions
```

If  use force delete, which means set the second paramter to true, `admin.topics().deletePartitionedTopic(topicName, true)`, It get deleted success.

**Comment by jiazhai** [comment]
It means we need force delete, even there is no messages produced.
Would like to close this issue. We could re-open it, If I was wrong.
