### ISSUE TITLE
Python 3 example on the getting started

### ISSUE THREAD

**Issue by bjonnh** [apache/incubator-pulsar#1395]
#### Expected behavior

Working "getting-started" guide example.

#### Actual behavior

The script producer script is raising an error:
```
Traceback (most recent call last):
  File "pulsar_pub.py", line 7, in <module>
    producer.send('hello-pulsar-%d' % i)
  File "./test/pulsar/venv/lib/python3.6/site-packages/pulsar.py", line 568, in send
    replication_clusters, disable_replication)
  File "./test/pulsar/venv/lib/python3.6/site-packages/pulsar.py", line 629, in _build_msg
    _check_type(bytes, content, 'content')
  File "./test/pulsar/venv/lib/python3.6/site-packages/pulsar.py", line 803, in _check_type
    raise ValueError("Argument %s is expected to be of type '%s'" % (name, var_type.__name__))
ValueError: Argument content is expected to be of type 'bytes'
```

#### Steps to reproduce

Just try the examples on page: https://pulsar.apache.org/docs/latest/getting-started/docker/
with Python3.

#### Steps to resolve

From a client side, replaced the send by:
```python
producer.send(('hello-pulsar-%d' % i).encode('utf8')) 
```

This should work with python2 too, at least recent versions of it.

#### System configuration
**Pulsar version**: Docker version 1.22.0-incubating
**Pulsar-client version**: pulsar-client==1.22.0 (from pip)

**Comment by merlimat** [comment]
Thanks @bjonnh for reporting this. Will fix the docs and examples
