### ISSUE TITLE
Docs about garbage collection are inaccurate/lacking

### ISSUE THREAD

**Issue by piotrblasiak** [apache/incubator-pulsar#1416]
In the docs (http://pulsar.apache.org/docs/latest/admin/GeoReplication/#creating-global-namespaces) the section "Delete a global topic" says:

> In Pulsar, a topic is automatically deleted when it’s no longer used, that is to say, when no producers or consumers are connected and there are no subscriptions

I believe it should say that it will also not be garbage collected if there are messages with retention > 0. And could be worth mentioning that you can turn this off with brokerDeleteInactiveTopicsEnabled=false.

**Comment by merlimat** [comment]
cc/ @lucperkins if you have bandwidth, or I can take it.

**Comment by lucperkins** [comment]
@merlimat I can handle it
