### ISSUE TITLE
skip-all/clear-backlog doesn't work if bookkeeper is outage

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1458]
#### Expected behavior

skip-all/clear-backlog should work if bookkeeper is outage due to backlog

#### Actual behavior

Tried to skip-all messages at the topic. Got 500.
Tried to skip-all messages at a partition. Got 404.
Tried to clear-backlog at namespace level. Got 500.

#### Steps to reproduce

introduce backlog to fill up disks to cause bookkeeper outage.

#### System configuration
**Pulsar version**: master

**Comment by sijie** [comment]
from @merlimat : "for the clear backlog. there is a very easy fix. If the cursor update fail on BK, we can fallback on the ZK write"

**Comment by merlimat** [comment]
Should be fixed in #1461. Please close when verified

**Comment by sijie** [comment]
@merlimat it seems #1461 doesn't actually address the problem. I am seeing 404. it seems to me that there is no topic reference - https://github.com/apache/incubator-pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L642 so it doesn't actually touch the skip-all logic.

**Comment by merlimat** [comment]
As we discussed, #1461 fixed the issue of updating cursors position when all bookies are not writable. 

There is still the issue of loading topics while all bookies are not writable, though it's a separate issue from just clearing backlog on a loaded topic.
