### ISSUE TITLE
Provide a tool to force delete a topic or a non-empty namespace

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1460]
*Problem*

If bookkeeper is outage, all the tools (skip-all/clear-backlog/unsubscribe) doesn't work (as #1458 #1459). There should be a tool to force delete a topic even there are active consumers.

Image in a large organization, if there is an outage due to disk filling up, you can't ask customers to stop all their applications to delete a topic. In this case, it would be good to be able to force delete a topic.

**Comment by merlimat** [comment]
Force delete topic added by @rdhabalia on #1656

**Comment by merlimat** [comment]
This was fixed in #1656 for 2.0.0 release
