### ISSUE TITLE
If bundle shed happened when creating consumer, create consumer will fail.

### ISSUE THREAD

**Issue by zhaijack** [apache/incubator-pulsar#1475]
Meet this issue when create a consumer with 15K partitions, PartitionedConsumer will fail with error:
```
 Mar 30 01:58:07 ip-10-0-0-58.us-west-2.compute.internal benchmark-worker[13068]: 01:58:07.474 [pulsar-client-io-8-4] WARN - [id: 0x67605525, L:/10.0.0.58:55438 - R:10.0.0.16/10.0.0.16:6650]          Received error from server: Namespace not served by this instance. Please redo the lookup. Request is denied: namespace=benchmark/local/ns-OwqJqWE
 Mar 30 01:58:07 ip-10-0-0-58.us-west-2.compute.internal benchmark-worker[13068]: 01:58:07.474 [pulsar-client-io-8-4] WARN - [persistent://benchmark/local/ns-OwqJqWE/test-WRF6MdM-0000-partition-1133][sub-000] Failed to subscribe to topic on 10.0.0.16/10.0.0.16:6650
```

We may need to do some change to the bundle shed processing, Or add retry lookup in client when meet this problem.

**Comment by zhaijack** [comment]
Seem it will get retry

**Comment by youurayy** [comment]
This definitely happens when 2 separate clients/producers register to the same multiple topics in parallel in a fast succession.

The one producer of the two which encountered these errors will not recover and keeps repeating the message. (Java client)
