### ISSUE TITLE
Retention 0mb and BacklogQuota 0mb

### ISSUE THREAD

**Issue by sschepens** [apache/incubator-pulsar#154]
It's not documented what setting a retention of 0mb actually does, neither with BacklogQuota.

By the way, both of this should actually mean no limit to be consistent with other settings.
If i'm not mistaken, setting those to 0mb will make brokers delete all data when they check.

In our case we want a retention based on time and not on size, so we actually want unlimited retention, and probably backlog quota too.

**Comment by sschepens** [comment]
@merlimat what do you think of this? there's now way right now to set an unlimited size retention or backlog quota.
Setting them to 0mb doesn't really make sense.
But if we want to maintain compatibility we could allow -1 as meaning of unlimited or something of the sort.

**Comment by merlimat** [comment]
Sorry @sschepens, I missed this issue back in the days. I just created #1135 and I'll create another PR to clarify in the documentation

**Comment by merlimat** [comment]
Added 2nd PR for docs changes: https://github.com/apache/incubator-pulsar/pull/1141

**Comment by sschepens** [comment]
Thanks for taking the time!

**Comment by merlimat** [comment]
Closing since both #1135 & #1140 were merged in 1.22
