### ISSUE TITLE
`No such ledger exists` error

### ISSUE THREAD

**Issue by bardock** [apache/incubator-pulsar#1571]
A broker owner of a topic partition is always failing trying to read a ledger because ledger doesn't exist in bookkeeper (we checked using `bookkeeper shell ledger`).

Broker log:

```
2018-04-13 14:16:11,677 - ERROR - [bookkeeper-ml-workers-38-1:ManagedLedgerImpl@1345] - [fury/global/8caa83e304674002a34f441f34f73f63-shipping-shipping/persistent/8caa83e304674002a34f441f34f73f63-shipping-shipping-partition-4] Error opening ledger for reading at position 7539625:0 - org.apache.bookkeeper.mledger.ManagedLedgerException: No such ledger exists
```

This error is happening always for the same partition and ledger id, since several weeks ago, even  namespace retention and message TTL are set to 7 days.

What is the recommended way to fix this particular case? How can we safely remove ledger id from partition metadata?

Thanks!

#### System configuration
**Pulsar version**: 1.20.0

**Comment by merlimat** [comment]
@bardock Skipping messages from that ledger should solve the issue. 

In particular you can get the internal stats for the topic: 

```
bin/pulsar admin persistent stats-internal $TOPIC
```

This should have the info on how many messages were still not acked on that ledger. I think the TTL is not working there because it's trying to read few of the messages to check the timestamps.

**Comment by merlimat** [comment]
For the skipping part: 

```
bin/pulsar admin persistent skip $TOPIC --subscription $SUBSCRIPTION --count 1
```

**Comment by bardock** [comment]
It worked great! 
Thank you Matteo

**Comment by zxbfeng** [comment]
> @bardock Skipping messages from that ledger should solve the issue.
> 
> In particular you can get the internal stats for the topic:
> 
> ```
> bin/pulsar admin persistent stats-internal $TOPIC
> ```
> 
> This should have the info on how many messages were still not acked on that ledger. I think the TTL is not working there because it's trying to read few of the messages to check the timestamps.


How did this problem("`No such ledger exists` error") arise? My pulsar broker aries the same problem!!

**Comment by zxbfeng** [comment]
> A broker owner of a topic partition is always failing trying to read a ledger because ledger doesn't exist in bookkeeper (we checked using `bookkeeper shell ledger`).
> 
> Broker log:
> 
> ```
> 2018-04-13 14:16:11,677 - ERROR - [bookkeeper-ml-workers-38-1:ManagedLedgerImpl@1345] - [fury/global/8caa83e304674002a34f441f34f73f63-shipping-shipping/persistent/8caa83e304674002a34f441f34f73f63-shipping-shipping-partition-4] Error opening ledger for reading at position 7539625:0 - org.apache.bookkeeper.mledger.ManagedLedgerException: No such ledger exists
> ```
> 
> This error is happening always for the same partition and ledger id, since several weeks ago, even namespace retention and message TTL are set to 7 days.
> 
> What is the recommended way to fix this particular case? How can we safely remove ledger id from partition metadata?
> 
> Thanks!
> 
> #### System configuration
> **Pulsar version**: 1.20.0

Did you know how did this problem arise ? The system config or zookeeper error or other reasons!!!

**Comment by XiaoyiPeng** [comment]
I  am also wander why. are there some PRs related with this issue.

who can explain? thanks.
