### ISSUE TITLE
Itermittent test timeout on PersistentFailoverE2ETest.testSimpleConsumerEventsWithoutPartition 

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#1614]
#### Expected behavior
The test is timing out several times. eg: 
https://builds.apache.org/job/pulsar_precommit_java8/724/testReport/junit/org.apache.pulsar.broker.service/PersistentFailoverE2ETest/testSimpleConsumerEventsWithoutPartition/ 

Test thread is blocked on: 

https://github.com/apache/incubator-pulsar/blob/8fbb926089effcadf59e199fe69ec65b4bbe4eae/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentFailoverE2ETest.java#L217

In particular it's waiting on the ` listener.activeQueue.take().intValue())`

https://github.com/apache/incubator-pulsar/blob/8fbb926089effcadf59e199fe69ec65b4bbe4eae/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentFailoverE2ETest.java#L102-L105

**Comment by sijie** [comment]
discussed with @merlimat - it is a bit unknown how the flaky test can happen after spending a few days on it. so we are going to defer this to 2.1.
