### ISSUE TITLE
Bookie's AutoRecovery affects publish times

### ISSUE THREAD

**Issue by bardock** [apache/incubator-pulsar#1625]
We are using Pulsar 1.20.0 and for each bookkeeper node we run two docker containers, one for bookie server and other for autorecovery. We use 3 bookies for ack and write quorum.

If a single bookie goes down, autorecovery process starts and publish times go up (avg from 3 ms to 40 ms, pct99 from 10 to 300 ms). We see that CPU usage of bookie nodes increase to 30-80%, mostly by autorecovery container.

Do you have any recommendation to improve publish times in this situation?

Some thoughts:
* Run autorecovery process on dedicated nodes in our BookKeeper cluster. I believe it is not supported in bk version shipped with pulsar 1.20. Is it possible to use bk 4.7 only for autorecovery nodes?
* Tweek write quorum. Maybe overreplicate by default, so if one single bookie goes down, it does not trigger autorecovery
* Limit recovery batch or CPU usage for autorecovery container. We do not like this option very much because replication will be slower

**Comment by bardock** [comment]
@merlimat, Do you have any thoughts on this?
Thanks!

**Comment by merlimat** [comment]
@bardock It is not supported in 4.3 (and it was not backported in yahoo branch). 

A workaround option is to temporarely disable "autorecovery"  with the bk shell CLI tool.
