### ISSUE TITLE
Fix Javadoc for ConsumerBuilder.patternAutoDiscoveryPeriod

### ISSUE THREAD

**Issue by haphut** [apache/incubator-pulsar#1722]
The [Javadoc](https://github.com/apache/incubator-pulsar/blob/9947f748e01f6cd8596e9fb49e16c090c6fda769/pulsar-client/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java#L266) for the parameter `periodInMinutes` in `ConsumerBuilder.patternAutoDiscoveryPeriod` does not seem to make sense: "periodInMinutes - whether to read from the compacted topic".

I'd expect to see something like "auto discovery period in minutes".

**Comment by merlimat** [comment]
Yes, it looks like a copy&paste artifact. @zhaijack  can you take a look?

**Comment by sijie** [comment]
This fixed by #1969
