### ISSUE TITLE
Proxy cannot be configured to work as proxy for both admin and client requests

### ISSUE THREAD

**Issue by ivankelly** [apache/incubator-pulsar#1796]
#### Expected behavior

When I start a proxy, I should be able to point both a client and an admin client at it, and expect it to work.

#### Actual behavior

By default, admin client will not work, as brokerServiceURL isn't configured (this should come from zookeeper, the key isn't even in the default config file). 

If I configure brokerServiceURL, then admin client works, but the client itself doesn't work, as it's trying to send binary protocol requests to a http endpoint.

**Comment by massakam** [comment]
This issue has been fixed by https://github.com/apache/incubator-pulsar/pull/1862
