### ISSUE TITLE
Proxy doesn't strip the request URL for admin requests correctly

### ISSUE THREAD

**Issue by ivankelly** [apache/incubator-pulsar#1797]
#### Expected behavior

Using proxy to do admin tasks should work.

#### Actual behavior

On client
```
org.apache.pulsar.client.admin.PulsarAdminException$NotAllowedException: HTTP 405 HTTP method PUT is not supported by this URL
```

From proxy log.
```
09:33:50.627 [pulsar-external-web-4-8] INFO  org.eclipse.jetty.server.RequestLog - 172.29.0.1 - - [17/May/2018:09:33:50 +0000] "PUT //172.29.0.4:8080/admin/v2/persistent/s3-offload-test/ns1/topic1/offload HTTP/1.1" 405 406 "-" "Jersey/2.25 (HttpUrlConnection 1.8.0_151)" 10
```

#### Steps to reproduce

Set up a broker with mostly default config (just set up zk stuff)
Set up a proxy with mostly default config (just set zk and brokerServiceURL)

I had 
```
brokerServiceURL=http://pulsar-broker1:8080
```
where pulsar-broker1 resolves to 172.29.0.5
172.29.0.4 is the ip of the proxy itself.

Admin client is created with:
```
PulsarAdmin admin = new PulsarAdmin(new URL("http://172.29.0.4:8080"), "", "")
```

**Comment by massakam** [comment]
This issue has been fixed by https://github.com/apache/incubator-pulsar/pull/1862
