### ISSUE TITLE
Topics definition missing as part of Pulsar-admin CLI 

### ISSUE THREAD

**Issue by dsambandam** [apache/incubator-pulsar#1835]
#### Expected behavior

I am trying to test Pulsar Standalone installation version 1.22.0 in CENTOS Ver#7 and ran into problems while testing the cluster setup with Produce/Consume Messages 

#### Actual behavior
Default Topic doesn't exists and Pulsar-admin CLI also doesn't show any Topics headers defined.
Let me know if I am doing something wrong .

Logs: 
root@vmb-pulsar-nso bin]# ./pulsar-client produce my-topic -m "hello"
17:14:16,374 ERROR Error while producing messages
17:14:16,375 ERROR Invalid topic name
org.apache.pulsar.client.api.PulsarClientException$InvalidTopicNameException: Invalid topic name
	at org.apache.pulsar.client.impl.PulsarClientImpl.createProducerAsync(PulsarClientImpl.java:166)
	at org.apache.pulsar.client.impl.PulsarClientImpl.createProducer(PulsarClientImpl.java:123)
	at org.apache.pulsar.client.cli.CmdProduce.run(CmdProduce.java:173)
	at org.apache.pulsar.client.cli.PulsarClientTool.run(PulsarClientTool.java:130)
	at org.apache.pulsar.client.cli.PulsarClientTool.main(PulsarClientTool.java:169)

root@vmb-pulsar-nso bin]# ./pulsar-admin topics
Was passed main parameter 'topics' but no main parameter was defined

Usage: pulsar-admin [options] [command] [command options]
  Options:
    --admin-url
       Admin Service URL to which to connect.
       Default: http://localhost:8080/
    --auth-params
       Authentication parameters, e.g., "key1:val1,key2:val2".
    --auth-plugin
       Authentication plugin class name.
    -h, --help
       Show this help.
       Default: false
  Commands:
    brokers      Operations about brokers
      Usage: brokers [options]

    broker-stats      Operations to collect broker statistics
      Usage: broker-stats [options]

    non-persistent      Operations on non-persistent topics
      Usage: non-persistent [options]

    resource-quotas      Operations about resource quotas
      Usage: resource-quotas [options]

    persistent      Operations on persistent topics
      Usage: persistent [options]

    ns-isolation-policy      Operations about namespace isolation policy
      Usage: ns-isolation-policy [options]

    clusters      Operations about clusters
      Usage: clusters [options]

    properties      Operations about properties
      Usage: properties [options]

    namespaces      Operations about namespaces
      Usage: namespaces [options]

#### Steps to reproduce

Followed the steps from the below link 
https://pulsar.incubator.apache.org/docs/latest/getting-started/LocalCluster/

#### System configuration
**Pulsar version**: 
1.22.0-incubating

**Comment by merlimat** [comment]
Hi @dsambandam. The website is already updated with the docs for release 2.0 which is imminent. In 2.0 we have simplified some of the concepts around naming and toolings. 

With the existing 1.22 release, please refer to the docs tagged for the release: http://pulsar.apache.org/docs/v1.22.0-incubating/getting-started/LocalCluster/

**Comment by dsambandam** [comment]
Hi @merlimat - Documentation looks fine but am not able to produce any messages to the topic with the standalone installation ..after the installation when you run pulsar-admin topics ( it throws an errors with missing definition) Does this mean my installation didn't go through successfully. Is there a way to test this ?

**Comment by dsambandam** [comment]
That works..thank you!
