### ISSUE TITLE
Underreplicated ledgers did not refresh when bookie was recovered

### ISSUE THREAD

**Issue by bardock** [apache/incubator-pulsar#1886]
Some bookies were down for about 2 hours and their ledgers were marked as underreplicated. When bookies went up again, the list of underreplicated ledgers did not change.

Is there a way to recreate the list of underreplicated ledgers? 
Replication is taking too long in our cluster.

Thanks!

#### System configuration
**Pulsar version**: 1.22

**Comment by sijie** [comment]
how many ledgers are marked as underreplicated? and what is the amount of data?

**Comment by bardock** [comment]
Hello @sijie 
In one of our clusters we currently have 21k ledgers marked as underreplicated. The bookie that went down has more than 300 GB of ledgers data.
In that cluster, we have 20 bookies running bookkeeper 4.3.1.91-yahoo. Each bookie server runs in its own docker container, and another container in the same machines runs autorecovery. When autorecovery process is replicating, it affects bookie's response times because they share resources. We are planning to create a dedicated cluster for autorecovery, but that's going to take a while.
In our current situation, we would like to regenerate the list of underreplicated ledgers, to avoid the replication process because they are already replicated to 3 bookies.
Thanks!

**Comment by sijie** [comment]
@bardock 

sorry for late response. 

I actually checked the logic in bookkeeper 4.3.1.91-yahoo. Replication worker actually checks if a ledger is under replicated or not before starting replicating it. So if a bookie went down and came back online, replication worker will find this ledger is not under replicated and clean it from underreplicated list. The logic seems to be right to me.

so if I understand this correctly, eventually the list of underreplicated ledgers should be cleared after the bookie came back online. did it?

**Comment by bardock** [comment]
@sijie 

Unfortunately, when bookie came back online, the underreplicated list didn't change significantly. Autorecovery is slowly replicating the ledgers (we see network bytes sent/received and a lot of cpu used by this container), but it could take days in replicate the entire list. Replication workers seem not to be detecting that the ledgers are already replicated.
What are your thoughts on that? Bookie is registered (we checked using `listbookies --readwrite`) 

Also, it is strange that replicating ledgers is so slow. Could this be related to having autorecovery process in a separated docker container? (we use host networking for both containers, bk server and autorecovery)

Thanks!

**Comment by sijie** [comment]
@bardock 

the replication workers checks the ledgers before actually replicating them. so if all the bookies come back online, the replication workers should detect that and mark those ledgers as replicated.

I think the problem might come from this change in yahoo branch-4.3.

https://github.com/yahoo/bookkeeper/blob/yahoo-4.3/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ServerConfiguration.java#L1416

it does 100% verification when attempts to replicating a ledger, which means it will read all the entries, which consume the network bandwidth and cpu, and it prevents replication worker mark ledgers as replicated.

I would suggest setting `auditorLedgerVerificationPercentage` to 0 in the bookkeeper.conf used by autorecovery. I believe that would address the issues you are seeing here and maybe #1625 as well.

**Comment by bardock** [comment]
@sijie, setting `auditorLedgerVerificationPercentage` to 0 has worked great. Thanks!

**Comment by merlimat** [comment]
@bardock just FYI, in BK-4.7 bundled in Pulsar-2.0 the default was already set to 0%
