### ISSUE TITLE
Support authentication in pulsar-functions

### ISSUE THREAD

**Issue by hrsakai** [apache/incubator-pulsar#1928]
We are planning to support authentication in pulsar-functions.
Please let me know if someone is already working.

**Comment by jerrypeng** [comment]
@hrsakai I don't believe anyone is working on authentication for functions.  It is awesome you guys are planning on implementing it for functions. It will be a great addition! Can you elaborate on how you plan on implementing authentication? Any design doc you can share?

**Comment by rdhabalia** [comment]
hi @hrsakai 
I was already working on it and it is implemented at [commit](https://github.com/rdhabalia/pulsar/commit/bae61d7442ea73d748229ef582a191dc5b6d20f8), I will create a PR soon.

**Comment by hrsakai** [comment]
@jerrypeng 
Since we have just started the discussion, there is no document yet.

@rdhabalia 
Great!
I'm looking forward to  the PR.

Thanks.

**Comment by hrsakai** [comment]
@rdhabalia 
I see, thank you.

**Comment by sijie** [comment]
This is implemented by #1935
