### ISSUE TITLE
[doc] Docker example and text out of sync

### ISSUE THREAD

**Issue by sslavic** [apache/incubator-pulsar#1929]
On https://pulsar.incubator.apache.org/docs/latest/getting-started/docker/ there's example command to run Pulsar on Docker, and text below explains some parameters from command, one of them is `--advertised-address 127.0.0.1`, it's covered but it is not actually used in example command.

**Comment by sijie** [comment]
Good catch. Does adding an paragraph explaining how to use that in an example work?

**Comment by merlimat** [comment]
Thanks for catching @sslavic. We need to remove the mention to `--advertised-address`. It was necessary before, but from 1.22 the Standalone doesn't require this argument anymore when running from inside Docker.
