### ISSUE TITLE
Provide Embedded Pulsar Runner

### ISSUE THREAD

**Issue by aahmed-se** [apache/incubator-pulsar#1933]
We should be able to start pulsar in a embedded jvm context.

Design can be similar to this.

https://github.com/prestodb/presto/blob/a31c0c95f65a80b355b2611b03b44b0bd5f47263/presto-kafka/src/test/java/com/facebook/presto/kafka/util/EmbeddedKafka.java

**Comment by sijie** [comment]
This has been implemented by #2080

**Comment by aahmed-se** [comment]
Here is an examples

https://github.com/streamlio/pulsar-embedded-tutorial/blob/master/src/test/java/org/apache/pulsar/PulsarEmbeddedTest.java

**Comment by aahmed-se** [comment]
@ganeshs try again I have me the repo public.

**Comment by ganeshs** [comment]
@aahmed-se Thanks for quick revert. The example code is under the package `org.apache.pulsar` and hence the start() method is accessible. It cannot be used outside of the package. This will require making the method public or protected

**Comment by ganeshs** [comment]
PR #3516
