### ISSUE TITLE
Non serializable client builder

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1943]
```
One of the main change concerns the 
configuration classes, replace by builders. Although ProducerBuilder and 
ConsumerBuilder interfaces implement Serializable, corresponding 
implementations aren't, because a pulsar client object is embedded. The 
schema object is also a problem for serialization.
```

**Comment by merlimat** [comment]
The problem has not an easy fix. The builders impl intrinsically hold references to non-serializable objects (eg: Client instance, or auth providers). 

I think in contexts that needs to serialize the config and dispatch to multiple nodes, a better options is to pass the config arguments in serialized form and then construct the client with builder on the target machines.

From Pulsar API perspective, we could ease that task by providing a way to load config from properties/yaml file. eg: 

```java
PulsarClient.builder().loadConfigFromProperties("my-conf.properties").build()
```

**Comment by sijie** [comment]
Can we do things like `PulsarClient.builder.withConf(ClientConfiguration).build()`?

**Comment by sijie** [comment]
I think the original clients and client configuration are not removed. so people should be able to still use the old api to construct the client, where client configuration is still serializable, right?

**Comment by gfouquier** [comment]
Yes, originals configuration classes are still there (sparkStreamingPulsarReceiver still used these), but marked as deprecated. Although i did not verify if changes in configuration fields have been reported in these classes. Some fields have different default values, a few names changes, maybe new field appears.

However, I don't think Builder interfaces should implement serializable if implementations can't

**Comment by sijie** [comment]
@gfouquier yes, agreed. I also don't think builder interfaces should implement serializable.

so it might still have values of having ClientConfiguration and let builder build the client with a provided configuration.

thoughts @merlimat ?

**Comment by merlimat** [comment]
Yes, we should removed `Serializable` from interfaces since there's no easy way to have any implementation to support that and then add a way to config from properties/yaml or map

**Comment by sijie** [comment]
@gfouquier I put up a PR for introducing `loadConf(Map<String, Object>)` for builders. in that way, you can use a Map for serializing the client settings. can you take a look and see if that works for your use case?

**Comment by gfouquier** [comment]
It will works for me since I already handle each configuration options from the command line, but it will less robust that calling method to set each options in case of name changes.

**Comment by sijie** [comment]
> but it will less robust that calling method to set each options in case of name changes.

that's true. I am using jackson object mapper to covert settings and reload to POJO. so the name changes should be caught and exception would be thrown to prevent any misconfiguration.

we will also enforce not changing field names and maintain backward compatibility as well.

hope this will reduce some of your concerns :)
