### ISSUE TITLE
Improve documentation of `RedeliverUnacknowledgedMessages`

### ISSUE THREAD

**Issue by awilliams** [apache/incubator-pulsar#2003]
#### Issue

I'd like to improve the binary protocol documentation for the [`RedeliverUnacknowledgedMessages`](https://pulsar.incubator.apache.org/docs/v2.0.1-incubating/project/BinaryProtocol/#command-redeliverunacknowledgedmessages) command. 

Specifically, I'd like to mention that the behavior when passing message ids differs depending on the subscription type. 

The only mention of message ids in the documentation is the following line:
> The protobuf object accepts a list of message ids that the consumer wants to be redelivered. If the list is empty, the broker will redeliver all the pending messages.

This statement is somewhat misleading, since it appears that message ids are ignored **unless** the subscription type is `Shared`. I'm basing this off observation and the following section of code:

https://github.com/apache/incubator-pulsar/blob/fd47532380d770e4fd78cabe71dea293fc2f0e06/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L1044-L1048

#### Request

I assume from reading the [source code](https://github.com/apache/incubator-pulsar/blob/9ad54466b462c69db395ceb3897bd1a87dd35f2a/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java#L309) that this behavior is there to ensure message ordering for non-shared subscription types.

If there is agreement that the documentation should mention this behavior, I could follow up with a documentation PR. Please advise.

#### System configuration

**Pulsar version**: `v2.0.1-incubating`, `v1.22.1-incubating`, possibly others

**Comment by sijie** [comment]
@awilliams I think your understanding is correct. feel free to submit a documentation PR
