### ISSUE TITLE
Python pulsar-client lacks multi-topic support

### ISSUE THREAD

**Issue by georgewilk01** [apache/incubator-pulsar#2033]
#### Expected behavior

According to documentation, post 1.7 API supports multi-topic subscriptions via regx and list. 

#### Actual behavior

I am unable to subscribe to a limited list of topics in my namespace using python client for pulsar with regx.

#### Steps to reproduce

Post message using command line as follows:
`bin/pulsar-client produce my-topic.1   --messages "user created"`

Subscribe consumer written in python as follows:
```
import pulsar

msg_address = "pulsar://localhost:6650/" 

client = pulsar.Client(msg_address)
consumer = client.subscribe('my-topic.*', 'my-subscription')

while True:
    msg = consumer.receive(timeout_millis=30000)
    print("Received message '{}' id='{}'".format(msg.data(), msg.message_id()))
    consumer.acknowledge(msg)

client.close()
```

#### System configuration
**Pulsar version**: apache-pulsar-2.0.1-incubating

**Comment by merlimat** [comment]
@georgewilk01 The multi-topic / regex subscribe for C++/Python client lib is currently being worked on and it's planned for 2.2 release. (PR at https://github.com/apache/incubator-pulsar/pull/1996 ) There are other newer features that got first introduced in Java client and we're now porting them to C++ (and wrappers). There's a github project here: https://github.com/apache/incubator-pulsar/projects/7 and we'll be adding a feature comparison matrix across all languages.

**Comment by georgewilk01** [comment]
Thank you for the info, @merlimat.

**Comment by merlimat** [comment]
@georgewilk01 btw: added feature comparison in wiki page https://github.com/apache/incubator-pulsar/wiki/Client-Features-Matrix

**Comment by sijie** [comment]
multi-topic and regex subscription support is added to python. it is actually released in 2.1.1 and will also be in 2.2.0

**Comment by Vanlightly** [comment]
Hi, I am using the 2.2.0 Python client and I don't have multi-topic or regex subscription support still. Am I missing something?

**Comment by merlimat** [comment]
@Vanlightly the `subscribe()` method can take a list of topics or a regex in the new version: http://pulsar.apache.org/api/python/#pulsar.Client.subscribe

**Comment by Vanlightly** [comment]
Thanks @merlimat, I missed that Python API page. It is working now.
