### ISSUE TITLE
Can't find code source in package org.apache.bookkeeper.mledger.proto

### ISSUE THREAD

**Issue by codelipenghui** [apache/incubator-pulsar#2142]
import org.apache.bookkeeper.mledger.proto.MLDataFormats.ManagedCursorInfo;
import org.apache.bookkeeper.mledger.proto.MLDataFormats.ManagedLedgerInfo;

**Comment by kuangye098** [comment]
Please read ReadMe.md in the protobuf directory, which will teach you how to build.

**Comment by codelipenghui** [comment]
Thanks
