### ISSUE TITLE
Cannot guarante message sequence with sequnceId in exclusive/failover mode

### ISSUE THREAD

**Issue by dbsd11** [apache/incubator-pulsar#2264]
#### Expected behavior

Expect consume message orderly in exclusive/failover mode with sequnceId. In fact, the sequence of messages is disorderly(partial orderly). Is it a problem of broker configuration?

**Comment by sijie** [comment]
Can you describe more what did you observe? If possible, provide us some example code to reproduce.

Also it would be good to know what do you mean here - sequence id and message id are different: sequence id is per producer, not globally to a topic. Message id is pet topic, which is increasing.

**Comment by merlimat** [comment]
@dbsd11 can you provide an example of the sequences you're seeing? 

Also, keep in mind, the sequence ids are tied to one particular producer

**Comment by dbsd11** [comment]
I got it. Thank you!
