### ISSUE TITLE
Document the settings to enable authorization

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#2282]
https://pulsar.incubator.apache.org/docs/latest/security/authorization/ is lacking instructions on how to enable authorization. for example `authorizationEnabled` is not documented.

**Comment by ivankelly** [comment]
@sijie look again. I added a bit when I was doing the TLS stuff, which added authorizationEnabled at least.

**Comment by sijie** [comment]
yeah the documentation is great!
