### ISSUE TITLE
Improve error message if authorization is not enabled

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#2283]
*Problem*

If `authorizationEnabled` is not enabled, authorization service is not set. All the accesses to this authorization service will throw NPE and clients will receive `Internal Server Error`. The message is meaningless. It is better to return a more meaningful message.

**Comment by ivankelly** [comment]
problem is visible when using grant/revoke permissions

**Comment by sijie** [comment]
also need to remove authorizationEnabled since there is already a authProvider setting
