### ISSUE TITLE
Pulsar broker start failure when set functionsWorkerEnabled=true

### ISSUE THREAD

**Issue by codelipenghui** [apache/incubator-pulsar#2328]
When i set functionsWorkerEnabled=true 

```shell
$ bin/pulsar broker
```

I got exception like this:

```lua
17:40:27.945 [main] ERROR org.apache.pulsar.functions.worker.SchedulerManager - Failed to create producer to function assignment topic persistent://public/functions/assignments
org.apache.pulsar.client.api.PulsarClientException$BrokerMetadataException: Namespace missing local cluster name in clusters list: local_cluster=pulsar-qa ns=public/functions clusters=[standalone]
	at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:798) ~[org.apache.pulsar-pulsar-client-original-2.2.0-incubating-SNAPSHOT.jar:2.2.0-incubating-SNAPSHOT]
	at org.apache.pulsar.client.impl.ClientCnx.handlePartitionResponse(ClientCnx.java:409) ~[org.apache.pulsar-pulsar-client-original-2.2.0-incubating-SNAPSHOT.jar:2.2.0-incubating-SNAPSHOT]
```

My broker conf:

```properties
# Name of the cluster to which this broker belongs to
clusterName=pulsar-qa
```

**Comment by codelipenghui** [comment]
Found the reason for this issue.

In zookeeper data of path named " /admin/policies/public/functions" has "replication_clusters":["standalone"]

When i set it to my cluster name. I can start the broker success.

**Comment by codelipenghui** [comment]
To change config pulsarFunctionsCluster in functions_worker.yml

**Comment by sijie** [comment]
@codelipenghui that's correct. the `functions_worker.yml` was shipped for standalone deployment. It has to be updated for cluster deployment. Let me improve the documentation on how to enable function worker in cluster mode in #2327

**Comment by sijie** [comment]
Closed the issue. Since the problem was addressed by updating `functions_worker.yml`, #2327 will be used for tracking the documentation updates.

**Comment by lelabo-marc** [comment]
Seems to be a mistake in the PR referenced.
I think the PR fixing this issue is https://github.com/apache/pulsar/pull/2335.

**Comment by rocketraman** [comment]
I have this same issue with running Pulsar on Kubernetes. I see that the script `gen-yml-from-env.py` is supposed to update `functions_worker.yml`, but I think the script is missing the value `pulsarFunctionsCluster` in INT_KEYS  `https://github.com/apache/pulsar/blob/60d2bfa389815b1769b36a0158059bfc3372a9a0/docker/pulsar/scripts/gen-yml-from-env.py#L30`
