### ISSUE TITLE
Initializing cluster metadata should handle /managed-ledger path better

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#2379]
`/managed-ledger` can be created automatically by brokers without initializing metadata. so in helm deployment, all pods are usually started at the same time. hence the race condition can happen between broker starts and initializing cluster metadata.

- broker starts triggering creating `/managed-ledger`
- cluster-metadata-initializer attempts to initialize cluster metadata and fail since `/managed-ledger` is already there.

it can be handled by adding more checks in `initContainer` before starting brokers. However I think we also need to improve the logic on initializing cluster metadata to better handle such corner cases.

**Comment by ivankelly** [comment]
@sijie @merlimat Seems to me like having the brokers initializing it is the problem. There's a bunch of metadata which is initialized once. Why is managed-ledgers an exception?

**Comment by sijie** [comment]
This is fixed by #2509 #2510
