### ISSUE TITLE
[java-client] ConnectionHandler: Log stack trace instead of printing

### ISSUE THREAD

**Issue by trathschlag** [apache/incubator-pulsar#2384]
https://github.com/apache/incubator-pulsar/blob/2bc48129bfb4433182f1b05a9008faef76e387ac/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java#L74

The pulsar java client is currently very noisy in case of connection loss and it cannot be muted, as the stack trace is printed with `.printStackTrace()`. Moving this to the logging system will allow developers to configure this behavior.

**Comment by merlimat** [comment]
@thrathschlag thanks for reporting. This printout was indeed committed by mistake when fixing a previous issue.
