### ISSUE TITLE
[documentation]: release notes link of old versions broken

### ISSUE THREAD

**Issue by jiazhai** [apache/incubator-pulsar#2386]
http://pulsar.incubator.apache.org/en/versions/
release notes link of old versions broken

![image](https://user-images.githubusercontent.com/6348208/44216699-1a24d800-a1a8-11e8-9acb-3a1329ea1a31.png)

seems file https://github.com/apache/incubator-pulsar/blob/master/site2/website/pages/en/versions.js not translated well.

**Comment by sijie** [comment]
@jiazhai nice catch! I think the problem comes from double-slashes - `//`. web browsers will think the link it is a URL instead of a path.
