### ISSUE TITLE
Android lambda exceptions for client

### ISSUE THREAD

**Issue by hakangs** [apache/incubator-pulsar#246]
#### Expected behavior

I have an android app, in which I have added Pulsar Client with gradle. It compiles fine with these additional settings in build.gradle file:

```
jackOptions {
    enabled true
}

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

#### Actual behavior

But when I run the app, I get the following exceptions and it fails:

```
Error:ChannelManager.java:363-364: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are io.netty.util.concurrent.GenericFutureListener
Error:NettyReactiveStreamsBody.java:113-114: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.lang.Runnable
Error:AsyncHttpClientConfigHelper.java:65-66: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
Error:AsyncHttpClientConfigDefaults.java:86-87: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.IntFunction
```

How can we reproduce the issue

Can it be because Android does not accept lambdas by default ? How can I achieve Pulsar Client to run in Android ?

Is there a 1.7 version compiled version of client jars ?

#### System configuration
**Pulsar version**: 1.16

**Comment by agarman** [comment]
Have you considered using the [WebSocket](https://github.com/yahoo/pulsar/blob/master/docs/WebSocket.md) client?

It'll be simpler than getting a bunch of Java 8 libraries to work (stably) in Dalvik.

**Comment by sijie** [comment]
the minimal requirement for java is java8.  and there is a websocket proxy, so you can use websocket api.
