### ISSUE TITLE
Multitopic subscription missing in most clients especially C++?

### ISSUE THREAD

**Issue by RobIsHere** [apache/incubator-pulsar#2463]
Pulsar in contrast to Kafka allows to make a topic per user, which is a big win. But if I do that, I'll get a huge number of topics.

To access these topics in a sane way, subscribing to multiple topics would be absolutely necessary or I would need to make a huge number of topic specific connections per processing node. 

I'd need either fast performance optimized processing in c++, or fast developed prototypical implementations in node.js. In node I could also use the c++ client as a module easily. So Java is just what I don't need.

How do you handle processing many topics in languages other than java?

**Comment by merlimat** [comment]
@RobIsHere This is already in progress and coming in 2.1.1 release which will be available in ~1 week.

See: 
 * C++ #1996
 * Go #2448
 * Python #2451

**Comment by RobIsHere** [comment]
Thank you! That's great! I'll use the C++ API directly ;)

**Comment by ivankelly** [comment]
Looks to be resolved.
