### ISSUE TITLE
MacOS: Could not find a version that satisfies the requirement pulsar-client==2.1.0

### ISSUE THREAD

**Issue by srids** [apache/incubator-pulsar#2568]
#### Expected behavior
Using pip3, I've tried to install the latest release of the pulsar-client version 2.1.0. I expected a clean install, given that version 2.1.0 has been released via pypi (link [here](https://pypi.org/project/pulsar-client/2.1.0/)).

#### Actual behavior

Unfortunately, there seems to be an error finding the 2.1.0 distribution. Error as below:

```
Could not find a version that satisfies the requirement pulsar-client==2.1.0 (from -r requirements.txt (line 54)) (from versions: 1.19.0, 1.20.0, 1.21.0, 1.22.0, 2.0.1)
No matching distribution found for pulsar-client==2.1.0
```

#### Steps to reproduce
On MacOS, install pulsar client as:
pip3 install pulsar-client==2.1.0

#### System configuration
MacOS High Sierra 10.13.6 (17G65)
Pulsar version: 2.1.0
Python version: 3.6.5
Pip version: 9.0.3

**Comment by sijie** [comment]
@srids can you provide some information about your macOS version?

Also this is the list of python client versions we published for 2.1.0-incubating release.

https://pypi.org/project/pulsar-client/#files

**Comment by sijie** [comment]
yeah I think we only publishes 37 for MacOS. is it possible for you to upgrade to 37, or you can only use 36?

**Comment by srids** [comment]
Apparently we cannot upgrade to 3.7 yet (some issues with Python 3.7 distribution for us).

**Comment by sijie** [comment]
@srids gotcha. we have a release 2.1.1 upcoming in 2 days. we can try to publish 37 for macos. does that work for you?

**Comment by srids** [comment]
you mean 36 for macos :) - yea that should work but think it will be consistent to publish 2.1.0 for 36 as its already done for Linux but not for MacOS.

**Comment by sijie** [comment]
@srids yes I mean 36. a release typically requires reviews and votes in apache software foundation. so if things are missing, we are fixing it in the next release :)

**Comment by srids** [comment]
ic. sounds good to fix in 2.1.1 then. thanks.

**Comment by sijie** [comment]
Closed this issue as question answered.

**Comment by Carmezim** [comment]
Any plans to support Python 3.9?
