### ISSUE TITLE
Android and IOS client support

### ISSUE THREAD

**Issue by pablichjenkov** [apache/incubator-pulsar#2581]
I am trying to build a Chat App with the purpose of testing Apache Pulsar. I wanted to make it in pure Android Java/Kotlin to avoid any possible oracle-java8 incompatibility either at compilation time or runtime.
I am able to run Pulsar server application on my local environment and send/receive messages using the pulsar-client program. However, I have not been able to connect to the server from Android.
The [official documentation](https://pulsar.incubator.apache.org/docs/latest/clients/WebSocket/#Producerendpoint-r2hxu) says that in order to send a message, a client should create a WebSocket connection to the broker endpoint and send a json formatted text with a key named **payload**. 
Following that I should be able to connect to the Producer endpoint with bellow code unless I am missing something.:

*Bellow code uses OkHttpClient library*
`
String wsUrl = "ws://192.168.70.1:8080/ws/v2/producer/persistent/public/default/my-topic";
webSocket = okHttpClient.newWebSocket(wsRequest, wsListener);
`

As soon as the connection is started the websocket listener invoke the Failure callback method.
Below message is shown in the logs by the okHttpClient:

`
16:43:53.904 [pulsar-client-io-71-8] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to pvaldes.local:6650 : io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'pvaldes.local' failed to resolve 'pvaldes.local.local' after 6 queries
16:43:53.904 [pulsar-client-io-71-8] WARN  org.apache.pulsar.client.impl.PulsarClientImpl - [persistent://sample/default/my-topic] Failed to get partitioned topic metadata: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'pvaldes.local' failed to resolve 'pvaldes.local.local' after 6 queries
16:43:53.905 [pulsar-web-54-6] WARN  org.apache.pulsar.websocket.ProducerHandler -  Failed in creating producer on topic persistent://public/default/my-topic: java.util.concurrent.CompletionException: io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'pvaldes.local' failed to resolve 'pvaldes.local.local' after 6 queries
`

Check code here [sample source code:](https://github.com/pablichjenkov/Pulsar-Droid/blob/master/app/src/main/java/com/ncl/pulsarj/MainActivity.java)

It seems like the netty domain name server is failing to resolve my local hostname. Any advice on why it is happening. **My setup is a pulsar standalone instance running on MAC Book Pro, Firewall Off**

Thanks in advance

**Comment by Adam-Kazberuk-Narvar** [comment]
Was a solution found to this?
I'm running into the same issue (coincidentally also setting up pulsar for websockets), I'm guessing it might also be a config issue, but having difficulty finding it

**Comment by merlimat** [comment]
@Adam-Kazberuk-Narvar I don't know the details but looks like the problem described here was due to some hostname resolution error from the websocket proxy to the broker service: 

```
io.netty.resolver.dns.DnsNameResolverContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'pvaldes.local' failed to resolve 'pvaldes.local.local' 
```

**Comment by Adam-Kazberuk-Narvar** [comment]
@merlimat, Yeah, honestly not super familiar with the inner workings yet. [Just tried getting the standalone Pulsar set up](https://pulsar.apache.org/docs/v1.19.0-incubating/getting-started/LocalCluster/), it appears to start and the internal test producer/consumers appear to function.

I'm guessing the issue is in the [Node.js implementation of producers/consumers](https://pulsar.apache.org/docs/latest/clients/WebSocket/#nodejs)
I'll report back if I find the cause

**Comment by pablichjenkov** [comment]
@Adam-Kazberuk-Narvar 
I resolved the problem by specifying explicitly the hostname when running the pulsar standalone. The problem was that my MAC DNS config was returning a wrong domain when resolving localhost. The standalone command has an option to explicitly set the host name you want Pulsar to be launched.
On another hand I created a simple sample using the websocket api with Android, check here:
https://github.com/pablichjenkov/Pulsar-Droid

Once I  find some time I will create one for iOS.

**Comment by Adam-Kazberuk-Narvar** [comment]
@pablichjenkov, @merlimat, thank you so much!

Just for documentation's sake (wish I read the comment!):
```
# Hostname or IP address the service advertises to the outside world. If not set, the value of InetAddress.getLocalHost().getHostName() is used.
advertisedAddress=127.0.0.1
```
Hitting
`ws://127.0.0.1:${webServicePort}/ws/v2/producer/persistent/public/default/my-topic`
appears to work now.

I'll call out the Nodejs example URLs won't work out of the box
`producer/persistent/my-tenant/my-ns/my-topic1`
Swapping them for the Python URL examples worked
`producer/persistent/public/default/my-topic`
