### ISSUE TITLE
broker api to increase number of partitions of broker

### ISSUE THREAD

**Issue by rdhabalia** [apache/incubator-pulsar#291]
#### Expected behavior

I think there is a real need and frequent ask for an api to increase number of partitions of a given topic. So, broker should have an api which increases number of partitions by following steps:
- fence topic
- disconnect producers and consumers on the topic
- increase partitions
- unfence topic 
Right now, it can be applicable for non-global topics only.

@merlimat any thought as we had this discussion before??

**Comment by merlimat** [comment]
> fence topic
> disconnect producers and consumers on the topic

This needs to happen on multiple brokers

> increase partitions
That's the easy part 😄 

> unfence topic
Again, coordinate multiple brokers, and then needs a way to communicate to producer consumers that they have to restart with the partition configuration. 

(All this setting aside any ordering breaking consideration)

**Comment by merlimat** [comment]
I think the 1st step should be to define what can be reasonably achieved and what the operation would look like for a user

**Comment by rdhabalia** [comment]
>This needs to happen on multiple brokers

That's correct. Therefore, i missed to list down another option here:
- create additional subscriptions for new partitions
- increase partitions in globalZk
- ask partitioned-topic owner brokers to invalidate partition-topic cache and disconnect all producers and consumers
- let producers/consumers reconnect (if any of the lookup broker failed/delayed to refresh partition-topic cache then in worst case we won't loose the data as subscriptions are already created) and next client restart can get it correctly. 

> I think the 1st step should be to define what can be reasonably achieved and what the operation would look like for a user

Correct. I think broker can only increase the number of partitions and can't allow to decrease as it requires to delete subscription.
API: updatePartitionedTopic(topic, numPartitions) // or incrementPartitions(topic, numPartitions)

**Comment by merlimat** [comment]
One point to consider is that when connecting to create a producer/consumer on a partition, the client doesn't indicate how many partitions it believes are available. Eg.: we don't specify partition 5 out of 16. 

That would make it easier for a broker to reject a producer/consumer with the wrong metadata information.

**Comment by rdhabalia** [comment]
>That would make it easier for a broker to reject a producer/consumer with the wrong metadata information.

I apologize but I couldn't fully understand this one. you are right that client doesn't send metadata-information(eg. 5 out of 16) to broker when create producer/consumer. So, you are suggesting that we should introduce a new field named `totalPartitions` in a request and if it doesn't match at broker then broker rejects so, client can do new lookup to get latest metadata?

**Comment by merlimat** [comment]
>  So, you are suggesting that we should introduce a new field named totalPartitions in a request and if it doesn't match at broker then broker rejects so, client can do new lookup to get latest metadata?

Yes, though I'm just bouncing ideas.. don't read too much into it.

> client can do new lookup to get latest metadata?

The challenge here is to make sure the client library reinitiates itself by correctly recreating all the individual producers/consumers. Also, what happens to clients with older client lib?

**Comment by rdhabalia** [comment]
> Yes, though I'm just bouncing ideas.. don't read too much into it.
Ok. :-)

yes, we can do that. with older lib (if `totalPartitions` not present) it will not reject producers/consumers and client might have to restart manually later on. but with this change at least client can get a chance to do new lookup.
However, we also have to handle usecase where new partitions falls under different bundle and broker which owns that bundle might not have received watch so broker itself may not have latest data.
