### ISSUE TITLE
Bookkeeper OOM

### ISSUE THREAD

**Issue by sschepens** [apache/incubator-pulsar#411]
We're getting OOM from bookkeepers only in a single cluster.
I'm attaching config file, an output of `jmap -histo` and a heap dump of a bookie experiencing OOM.
We're setting heap space to 4g, I wonder if  `dbStorage_rocksDB_blockCacheSize=4294967296` could be the issue, does this memory come from direct memory? or heap space?

By the way, we've disabled `readAheadCache` because we were getting horrible performance, directly reading from disk stressed the disks much more and proved to be more effective at draining backlog, though this seems strange.

[jmap-histo.txt](https://github.com/yahoo/pulsar/files/1004483/jmap-histo.txt)
[bookkeeper.conf.txt](https://github.com/yahoo/pulsar/files/1004487/bookkeeper.conf.txt)
[ip-10-64-102-226-heap.bin](https://drive.google.com/file/d/0BxW5XJcTWdDgOGtETVNOdk1vVjg/view?usp=sharing)

**Comment by merlimat** [comment]
> We're setting heap space to 4g, I wonder if dbStorage_rocksDB_blockCacheSize=4294967296 could be the issue, does this memory come from direct memory? or heap space?

The rocksdb memory is allocated from the C++ library, and it's completely outside the JVM. It won't contribute to neither heap or direct memory.

I tried to open the heap dump with several tools but it looks invalid and the fail to process it.

From the histo, it looks like the reason for the OOM are the 3.7G of heap retained in `long[]` arrays

```
 num     #instances         #bytes  class name
----------------------------------------------
   1:           854     3732598224  [J
   2:          4249        4305384  [Ljava.lang.Object;
...
```

Can you take a look where the references to these arrays are coming from?

In any case, if you are storing a lot of entries for long time, try to increase the JVM heap size.

You can check the current heap & direct mem utlization in bookies on the `data/bookkeeper/bookie-stats.json`: 

```
...
 "jvm.DIRECT_MEMORY_TOTAL" : 4294967296,
  "jvm.DIRECT_MEMORY_USED" : 178203,
  "jvm.GC_OLD_COUNT" : 0,
  "jvm.GC_OLD_TIME" : 0,
  "jvm.GC_YOUNG_COUNT" : 2,
  "jvm.GC_YOUNG_TIME" : 102,
  "jvm.HEAP_TOTAL" : 2147483648,
  "jvm.HEAP_USED" : 145288440,
  "jvm.NETTY_POOL_ALLOCATED" : 268435456,
  "jvm.NETTY_POOL_USED" : 1056768,
...
```

**Comment by sschepens** [comment]
@merlimat we're gonna try incrementing heap without decrementing rocksdb cache then.
Do you know why  `readAheadCache` is not working for us? we have desabled it now.

**Comment by estebangarcia** [comment]
@merlimat We increased our heap to 8GB and had the same issue. We took another dump (you can download it here: https://s3.amazonaws.com/pulsardumps/dump_ip-10-64-103-165.tar.gz)

We found the same behaviour with the long[]:
![screenshot from 2017-06-05 16-01-49](https://cloud.githubusercontent.com/assets/16657038/26798779/4e9495c4-4a08-11e7-94ee-d1235d46ac76.png)

These are the objects referencing those longs:

![screenshot from 2017-06-05 15-57-04](https://cloud.githubusercontent.com/assets/16657038/26798780/4e9685be-4a08-11e7-99fe-14a7525a6ca6.png)

Heap Usage of the last two days:

![screenshot from 2017-06-05 16-17-19](https://cloud.githubusercontent.com/assets/16657038/26799087/7dbce584-4a0a-11e7-931a-b6e39dfba126.png)

**Comment by merlimat** [comment]
@estebangarcia I took a look at the heap dump. 

It seems like there are a lot of entries that were stored into the read cache. Just the hashmaps that are used to track the read cache are taking 1.7Gb of heap memory.

You are saying that you have the read-ahead cache disabled, right? In any case, the entries are inserted into read-cache after reading (the intention is to save eventual subsequent reads, though it might not be the best option...).

I think you can reduce the heap size needed by the hashmap, if you reduce the size of the read-cache: 

```properties
dbStorage_readAheadCacheMaxSizeMb=12288
```

Try to tune this down to something like 512m or 1G and the memory usage should not grow much.

**Comment by merlimat** [comment]
To clarify, the 12Gb configured there are referring to direct memory where the entries are stored in the read cache.

On top of it, we need to keep a hashmap (in JVM heap) to index the entries with their location in the direct memory. For each entry there will be (8 * 4) bytes + the overhead of the hasmap (target fill rate is 66%, before triggering a hashmap expansion).

**Comment by sschepens** [comment]
@merlimat, thanks for the help.
Have you considered using a full off-heap map for this use case? I found this two libraries https://github.com/cfelde/BinaryOffheapHashMap and https://github.com/snazy/ohc
Using a full off-heap map would allow the readahead cache to grow indefinitely without affecting heap and GC, the only downside is that keys have to be serialized and copied for usage, which would introduce a small overhead, this would be great for misses most of all, if this is seen as a problem we could use something like a HyperLogLog on heap to know if a key is present in the off-heap cache before accessing it.

**Comment by sijie** [comment]
I think the question here is answered. Close this issue. We can open a new issue if we need to introduce the off-heap entry index map.
