### ISSUE TITLE
Introduce non-persistent topic

### ISSUE THREAD

**Issue by rdhabalia** [apache/incubator-pulsar#451]
Usecase:
As per discussion at #438 : We have received multiple usecase scenarios from multiple groups and teams which require a non-persistent topic in pulsar to stream messages similar like zeroMq.
- consumer wants to read only recent messages and doesn't care about stale or old messages
- client doesn't require msg persistent guarantee so, broker can immediately delivers message to consumer without persisting it which helps to get very low publish-latency on a topic.

**Changes**:
Broker will support non-persistent topic to support above usecase. Broker doesn’t persist messages for non-persistent topic but it immediately delivers message to already connected consumers and replicators. It also supports partitioned-topic and global-topic. Broker replicates non-persistent messages to configured replicated cluster..

**Client Changes:**
Client can create producer and consumer on non-persistent topic using similar API as persistent-topic. However, non-persistent topic name protocol starts with `non-persistent` instead `persistent`. 
e.g.
`non-persistent://my-property/cluster/namespace/topicName`
**changes**:
- Client provides topic name that starts with `non-persistent` prefix.
- Broker keep pushing messages to consumer as soon as producer publishes so, if consumer is not fast enough to consume messages and internal receive queue is full with the received messages then client consumer will drop newly incoming messages.. Therefore, client must tune consumer receive-queue size based on consume rate.

**Broker Changes:**
- Broker creates a special non-persistent topic entity which manages non-persistent topic’s producers, consumers and replication.
- Broker will not cache or persist published message and try to immediately dispatch messages to connected subscribers and replicators.
- **Rate limiting:** Broker must be configurable with rate-limiting to limit rate of publish messages on each topic to prevent over usage of n/w bandwidth by a specific topic. Broker fails published message once publish rate goes beyond rate-limiting.
- **Isolate broker to load only non-persistent topics:** Broker should be configurable in such as way that it can reject ownership of non-persistent topic or broker only owns non-persistent topics. It helps to isolate set of brokers which can only serve non-persistent topics. It also requires load-manager changes to obey broker’s isolation.

**Stats:**
- Broker supports stats api which provides similar stats as persistent-topic stats.

**Comment by jai1** [comment]
Just a thought

>  if consumer is not fast enough to consume messages and internal receive queue is full with the received messages then client consumer will drop newly incoming messages

If the dropping mechanism will be on client side then can we drop old messages in receiver queue and fetch more messages from broker (via CommandFlow) rather than dropping the newly incoming messages - so that even though there is a pause in the consumer end we always deliver the latest messages. The Usecase also states that consumer only wants recent messages - no point giving it 1000 old messages (Receiver queue size)

**Comment by msb-at-yahoo** [comment]
You need something on the broker side to defend from hostile clients.

On the client side, how old is too old before dropping? A long GC pause may lead to surprising behavior, for example.  Make it a config setting with a default of 30s?

**Comment by rdhabalia** [comment]
> If the dropping mechanism will be on client side then can we drop old messages in receiver queue 

Yes, I think we can remove oldest message in the queue if queue is full and then can add newly incoming message.

> You need something on the broker side to defend from hostile clients.

Right now, at broker side we have rate limiter for publish message where publisher can publish 1K message per second and broker fails publish over that limit.

> On the client side, how old is too old before dropping? A long GC pause may lead to surprising behavior.

Actually, client only drops message if consumer is slow and not able to consume already received messages and internal receive queue is full. So, if consumer can tune message queue according to consumption rate so, it doesn't have to drop any of the message.

**Comment by merlimat** [comment]
> You need something on the broker side to defend from hostile clients.

@msb-at-yahoo We have not big protections so far against hostile clients even for persistent topics. The protections that are in place are for back-pressure or work cooperatively with the client library. There is little protection against circumventing these mechanisms.

> Right now, at broker side we have rate limiter for publish message where publisher can publish 1K message per second and broker fails publish over that limit.

@rdhabalia A fixed rate limit is not very flexible and it can be tricky to set. Also, if you do it at the broker level, it applies to everything. 
In general, I should be able to send/receive as fast as possible and if any bottleneck is reached, then the backpressure should apply all the way back to the source.

In case on non-persistent, you can still enforce a max number of in-flight messages from a particular connection. 

In case the consumers are not able to keep up with the rate, then the messages should just be dropped.

**Comment by rdhabalia** [comment]
> In case on non-persistent, you can still enforce a max number of in-flight messages from a particular connection.

Sure, right now we have added rate-limiting per [non-persistent-topic](https://github.com/rdhabalia/pulsar/blob/34534370d7bb71fe83175a818090f951824696f2/pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/non/persistent/NonPersistentTopic.java#L189), but yes, I think it's better to enforce max number of in-flight messages per connection rather. I will make that change in PR.

**Comment by merlimat** [comment]
Right now the logic is based on "messages in flight to bookies" so we can easily apply backpressure there if we cannot write to bookies fast enough. 

For non-persistent, though, what can we use for metric? 

On the flip side, the client can keep sending messages anyway (irrespectively of us trying to tell him not to do it). But if the act of action when getting a message and the consumers are not available/ready/... is to drop it on the floor, then do we need rate limiting?

The next question is: should the producer adapt to the speed of consumers or should the messages be dropped?

In persistent mode, producers and consumers are isolated by the storage, which can be thought as an *infinite* buffer. So the backpressure is only applied on *persisting* the message to storage, irrespective of the consumption side.

**Comment by rdhabalia** [comment]
> But if the act of action when getting a message and the consumers are not available/ready/... is to drop it on the floor, then do we need rate limiting?

Right now, we do rate limiting as soon as message is published and if it is able to acquire permit then it will send message to consumer else it fails the publish with `TooManyRequestError`. So, broker does rate limiting even without any consumer connected.

> The next question is: should the producer adapt to the speed of consumers or should the messages be dropped? 

But right now broker keeps pushing message data to consumer without considering consumer's permit so, broker and producer don't have knowledge about how consumer is doing in terms of consumer's consumption rate. So, it will be hard to adapt consumer's speed.

> For non-persistent, though, what can we use for metric?

I was thinking to have 1 semaphore per connection and it acquires permit as soon msg is received and release permits once that message is delivered to all consumers and broker doesn't need that message in memory. In that way, per connection we can control max memory. And if we want to control n/w bandwidth then we may need rate-limiting to control msg in-rate/out-rate ?

**Comment by merlimat** [comment]
> Right now, we do rate limiting as soon as message is published and if it is able to acquire permit then it will send message to consumer else it fails the publish with TooManyRequestError. So, broker does rate limiting even without any consumer connected.

What is the behavior of the client library when receiving `TooManyRequestError`? Will it retry? Send the error to application? Exponential backoff?

If the app is not retrying, then silently dropping the message on the broker would be equivalent, because you're not exactly doing "rate limiting" in the sense to force the client to a certain speed, but rather discarding everything on top of a certain rate.

In any case, if the consumer is able to consume above the rate limiting threshold, why not just send to the consumer? The load-balancer should then take care of placing the topic into an appropriate broker.

>But right now broker keeps pushing message data to consumer without considering consumer's permit so, broker and producer don't have knowledge about how consumer is doing in terms of consumer's consumption rate. So, it will be hard to adapt consumer's speed.

The dispatcher knows the permits for a particular consumer, right? or am I missing context here?

> I was thinking to have 1 semaphore per connection and it acquires permit as soon msg is received and release permits once that message is delivered to all consumers and broker doesn't need that message in memory

But that only would help if the dispatching is done in background threads. If you dispatch from same thread where you read from the producer, then you don't need the semaphore.

**Comment by rdhabalia** [comment]
> The dispatcher knows the permits for a particular consumer, right? or am I missing context here?

In non-persistent topic as we don't have privilege to persist message so, broker dispatches message to consumer as soon as it receives message so, broker doesn't consider consumer's permit and it keeps delivering messages to consumer in [background thread](https://github.com/rdhabalia/pulsar/blob/34534370d7bb71fe83175a818090f951824696f2/pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/non/persistent/NonPersistentTopic.java#L192). 

> What is the behavior of the client library when receiving TooManyRequestError? Will it retry? Send the error to application? Exponential backoff?

Right now, producer handles `TooManyRequestError` same as other error and in that case it closes the connection and reconnect with broker and resend those messages again from the `pendingMessages` queue. In case that queue will be full then client-library will default block/fail the callback.

**Comment by saandrews** [comment]
> Right now, we do rate limiting as soon as message is published and if it is able to acquire permit then it will send message to consumer else it fails the publish with TooManyRequestError. So, broker does rate limiting even without any consumer connected.
Instead of failing the publish, isn't it better to drop the old messages? In cases like many different non persistent consumers connected and trying to consume the message, some of them might be running slow than the rest. So, it's better to let the producer continue producing the events and allow the fast consumers to receive while the slow consumers might miss some.

**Comment by merlimat** [comment]
> broker doesn't consider consumer's permit and it keeps delivering messages to consumer in background thread.

Why not? You can check that if you don't have permits, or the connection is not writable you throw the message away.

> Right now, producer handles TooManyRequestError same as other error and in that case it closes the connection and reconnect with broker and resend those messages again from the pendingMessages queue. In case that queue will be full then client-library will default block/fail the callback.

But then you're flooding the broker again, right? For the broker it's anyway less expensive to throw the message away immediately and to say "ok" to producer.

**Comment by merlimat** [comment]
> Instead of failing the publish, isn't it better to drop the old messages?

That you can only do if you are queuing the messages in the broker. If you dispatch immediately to the consumer, when the consumer is saturated you can only drop the *new* messages.

**Comment by rdhabalia** [comment]
> Why not? You can check that if you don't have permits, or the connection is not writable you throw the message away.

The only reason is: as consumer cares about newly published messages so, broker can keep dispatching the message and if client queue is full then client can discard old message and try to consume newly added message. So, in that way client always sees new messages and forget old ones like live-streaming. If we think consuming old message vs new message is fine then we can take permits approach and dispatch only if permit is available.

> For the broker it's anyway less expensive to throw the message away immediately and to say "ok" to producer.

Sure. But only drawback is publisher is keep thinking that message is being published successfully and broker silently drops it and there will not be any visibility for number of dropped messages. Probably then we can show these numbers in stats: msgInRate and msgDroppedRate for client visibility.??

**Comment by rdhabalia** [comment]
Alright from all suggestions above we have two approaches for rate limiting publish and delivery of messages. 

**Consumer:**
**Approach 1: Consider consumer permits:** Broker should consider consumer's permit and dispatch message accordingly else broker drops the message if consumer doesn't have permit when consumer's queue is full.
**Approach 2:  Don't consider consumer permit:** broker doesn't consider consumer permits and keep pushing published messages. If consumer is slow enough to consume messages and queue is full then consumer can discard old message from the queue and insert new message so, consumer can always have new messages and doesn't care about old messages.

**Producer:**
Broker can control max in-flight messages per connection and if broker receives messages beyond that limit then
**Approach 1: broker drops message:** Broker silently drops the message and doesn’t deliver to any consumer and send success to publisher. In this approach publisher will not know if message is actually successfully published or not.

**Approach 2: client does backoff:** Broker sends publish failure to producer and doesn’t deliver to any consumers. Client-producer will receive “TooManyRequestError” and client fails published message and also backoff for 100 msec. So, during that 100 ms if client tries to produce message it will immediately gets publish failure without sending request to broker. With this approach client will at least know about publish-failure and with backoff it will not publish messages for broker during backoff time.

@merlimat @saandrews : any thoughts which one we should take.

**Comment by merlimat** [comment]
#### Consumer

> Approach 2: Don't consider consumer permit: 

Even if the consumer drops the messages, you're going to flood it with messages. 
I think approach 1 is better, use existing flow control mechanism, and requires no changes in the client code.


#### Producer

> Approach 1: broker drops message: Broker silently drops the message and doesn’t deliver to any consumer and send success to publisher. In this approach publisher will not know if message is actually successfully published or not.

What does that mean for the message to be successfully published in this context?
If the message is to be stored in broker's memory, then we are already "successful", since the message already reached that point. 
I think the publish outcome should be detached by what action the broker can take later (eg: drop the message if consumers are slow or not available)

> Approach 2: client does backoff: Broker sends publish failure to producer and doesn’t deliver to any consumers. Client-producer will receive “TooManyRequestError” and client fails published message and also backoff for 100 msec. So, during that 100 ms if client tries to produce message it will immediately gets publish failure without sending request to broker. With this approach client will at least know about publish-failure and with backoff it will not publish messages for broker during backoff time.

I think this approach would break the basis of pub-sub (detaching producer and consumers). In this case you're going to slow down the producer according to consumers capacity.


So, my vote goes on 1  & 1

**Comment by rdhabalia** [comment]
> So, my vote goes on 1 & 1

Sure.

> I think this approach would break the basis of pub-sub (detaching producer and consumers). In this case you're going to slow down the producer according to consumers capacity.

Actually that's what not I mean here, we should not slow down producer according to consumer's capacity. What I mean if producer is publishing more than rate-limiting per-connection then broker can give publish-failure and producer at client-lib handles this failure by doing two things:
1. notify client producer with publish failure.
2. set back-off for X millisecond (eg. 100) and in that duration producer will get publish failure immediately at client-lib so, producer can't send more publish-msg request to broker in that back-off duration.
- Or as you mentioned: producer can have option to configure where producer is fine for message to be dropped silently.

**Comment by joefk** [comment]
@merlimat  I think we are mixing 2 things up. 

1) How many messages can a producer produce?  This is unrelated to consumption.  There is a limit, whether configurable or imposed by resources. What happens when that limit is reached?

Drop silently/Drop with notification

2) What happens when consumers cant keep up with publishers?  

Drop current/Drop oldest.

Let's figure whether we should support these use cases, and then discuss how to do it

**Comment by rdhabalia** [comment]
@merlimat : created [PIP](https://github.com/apache/incubator-pulsar/wiki/Non-Persistent-topic) for the issue. and also have PR open for #538 and #452 .

**Comment by bruth** [comment]
Sorry to be commenting on a closed issue, but I wanted to ask how *cheap* it is to create a non-persistent topic? Would it be able to handle the use case of a one off request/reply? The client subscribes to a randomly named non-persistent topic, it publishes a request to a topic and includes the *reply* topic name expecting the consumer to send back a message on that topic at some point.

I am currently using [NATS](https://github.com/nats-io/gnatsd) for this use case, but Pulsar would be very attractive if it can handle both cheap non-persistent topics and fully durable ones.
