### ISSUE TITLE
Some Commands are missing in binary protocol specification

### ISSUE THREAD

**Issue by t2y** [apache/incubator-pulsar#472]
I found some commands are missing in [Pulsar binary protocol specification](https://github.com/yahoo/pulsar/blob/master/docs/BinaryProtocol.md), but they're exist in [PulsarApi.proto](https://github.com/yahoo/pulsar/blob/master/pulsar-common/src/main/proto/PulsarApi.proto).

* CommandUnsubscribe
* ~~CommandRedeliverUnacknowledgedMessages~~
* CommandConsumerStats
* CommandConsumerStatsResponse

Could you add the specification of them?

As an aside, I'm  a Japanese, so I can translate them into [locale/ja](https://github.com/yahoo/pulsar/tree/master/docs/locale/ja), after they would be published.

#### Expected behavior

All commands are documented in Pulsar binary protocol specification.

#### Actual behavior

Some commands are missing.

**Comment by merlimat** [comment]
@jai1 Can you add the docs about the Consumer stats commands in the protocol definition?

**Comment by dmitris** [comment]
NB - the binary protocol specification is now at https://github.com/apache/incubator-pulsar/blob/master/site/docs/latest/project/BinaryProtocol.md (or https://github.com/apache/incubator-pulsar/blob/master/site/ja/project/BinaryProtocol.md for Japanese)

**Comment by lucperkins** [comment]
The Protobuf API is now comprehensively documented (and always up to date) here: http://pulsar.incubator.apache.org/docs/latest/project/BinaryProtocol/

I think that this issue can be closed.
