### ISSUE TITLE
Speed up CPP Unit Tests

### ISSUE THREAD

**Issue by jai1** [apache/incubator-pulsar#537]
Currently, CPP Unit Tests take around 7 minutes to complete. By using gtest-parallel I see that we can complete the tests in 55 seconds, which 7 times faster.

Only problem is that currently 1/72 tests fail when run in parallel, need to revisit the test logic get them to pass with gtest-parallel.

    5081 ms: ./tests/main BasicEndToEndTest.testMessageListener

**Comment by rdhabalia** [comment]
> By using gtest-parallel I see that we can complete the tests in 55 seconds, which 7 times faster.

As tests run in parallel so, should we make sure that topic name in all tests are different else tests may fail intermittently as they share same broker instance?
