### ISSUE TITLE
Problems in lookup flow in C++ Client

### ISSUE THREAD

**Issue by jai1** [apache/incubator-pulsar#551]
# Issues:-

1. **Client Stops Doing Lookups**
In case of non graceful shutdown, if the ClientConnection object is not destroyed within first backoff time (0.1 seconds) then the consumer/producer will no longer attempt to reconnect to the broker - which may lead to Timeouts and queue full in case of producer and backlog in case of consumer.

2. **Locking inconsistencies in Lookup Logic**
In the following methods, we check/change the clientConnection_ weakPtr outside a lock
- ProducerImpl.disconnectProducer()
- ConsumerImpl.disconnectConsumer()
- HandlerBase.grabCnx()
- ConsumerImpl.handleCreateConsumer() 

3. **Duplicate lookups happen on the client side**
(A) During a graceful shutdown, the broker sends CLOSE_PRODUCER / CLOSE_CONSUMER command to the client, which triggers the reconnection logic. 
(B) After the connection is closed the ClientConnection.close() also triggers the reconnection logic for all registered consumers/producers. 

If (A) doesn't complete before (B) then lookups and CREATE_PRODUCER / CREATE_CONSUMER commands are sent twice - this is not a functional issue because the broker returns success for the duplicate command but this leads a twice the required number of lookups.

4. **Duplicate CLOSE_PRODUCER and CLOSE_CONSUMER triggered by the broker**
Not sure why this is happening or it's side effects.

**Note:** Will attach the relevant log files with the Pull Request for the fixes.

**Comment by merlimat** [comment]
@jai1 can you open individual issues for the 4 bugs? Or at least the fixes should come in separate PRs

**Comment by merlimat** [comment]
@jai1 Were all the 3 items in this issue fixed in 1.19?

**Comment by jai1** [comment]
Yes the three client side issues were fixed, but I didn't get a chance to look at the broker side code (fourth issue). Will fix it in 1.20

**Comment by jai1** [comment]
Couldn't reproduce the 4th issue - rest all are fixed
