### ISSUE TITLE
Link to website leads to 404

### ISSUE THREAD

**Issue by thedrow** [apache/incubator-pulsar#571]
#### Expected behavior
I should be able to access the project's website.

#### Actual behavior

I got 404 page not found when accessing  https://pulsar.incubator.apache.org

#### Steps to reproduce

Go to  https://pulsar.incubator.apache.org

#### System configuration
**Pulsar version**: N/A

**Comment by merlimat** [comment]
Hi @thedrow, we're still in the transition phase into the Apache infrastructure. 

At this point the website is ready to go and we're waiting for Apache INFRA to setup the publishing bridge. See https://issues.apache.org/jira/browse/INFRA-14587

It should be up in the next few days and I'll update this issue.

**Comment by dave2wave** [comment]
It is up now!
