### ISSUE TITLE
Upgrading to c++11

### ISSUE THREAD

**Issue by jai1** [apache/incubator-pulsar#579]
I want to upgrade the client to use C++11 - as per my discussion with @msb-at-yahoo as long as the interface does **not** use C++11 features, the change will be backward compatible.

@merlimat @saandrews - What is your take on this? Do you foresee any problems if we upgrade to C++11 and not use any C++11 features in the interface?
If not then I can start work on the same.

**Comment by merlimat** [comment]
If @msb-at-yahoo says it works, I 100% trust him.

A couple of questions : 
 1. Why not C++14 ? 
 2. Which minimum GCC version do you plan to target?

**Comment by jai1** [comment]
Since nobody else is waiting on this change I would like to take divide the work into three parts and deploy each part to production before making the next change:-
a. Upgrade to C++11 and clean up the code
b. Upgrade the compiler (version not decided)
c. Upgrade to C++14 

So in a span of six weeks (two pulsar releases), the entire thing should complete.

**Comment by merlimat** [comment]
Yes, I would suggest to replace all the usages of `boost` features with the correspondent c++11. 

Also, if you find it useful, you can create a "Project" in Github to track all the various tasks in tickets.

**Comment by saandrews** [comment]
Yeah, lets move forward with c++11 first. We should replace the usage as
well as long as they are compatible.

**Comment by jai1** [comment]
> Also, if you find it useful, you can create a "Project" in Github to track all the various tasks in tickets.

None of us have permission to create a project.

**Comment by merlimat** [comment]
> None of us have permission to create a project.

Try now

**Comment by jai1** [comment]
Was able to create the project 
Closing the issue - will track the progress via project
