### ISSUE TITLE
Documentation for deployment of a single cluster in a data center

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#621]
Current deployment section in Pulsar for bare metal directly talks about deploying clusters across different geographical locations. However, most of the people who want to try it out - will try in a single cluster consisting of few machines 4-6 for evaluation before they recommend. Hence, it will be easier for users if we have multiple sections such as

 * Deployment in a single cluster 
 * Deployment for multiple clusters (across data centers)

**Comment by merlimat** [comment]
cc/ @lucperkins

**Comment by sijie** [comment]
This is fixed by multiple PRs.
