### ISSUE TITLE
unable to generate NarSystem class

### ISSUE THREAD

**Issue by maskit** [apache/incubator-pulsar#681]
#### Expected behavior

No warnings during build.

#### Actual behavior

```
[INFO] --- nar-maven-plugin:3.1.0:nar-system-generate (default-nar-system-generate) @ pulsar-checksum ---
[WARNING] NAR: no system package specified; unable to generate NarSystem class.
```

#### Steps to reproduce

```
mvn install -DskipTests
```

#### System configuration
**Pulsar version**: master c51eaad9745d36d737b30d645fa1db753ae87246
**OS**: macOS 10.12

**Comment by merlimat** [comment]
Fixed in #695. Verified in build output that the warning is gone: 
https://builds.apache.org/job/pulsar-pull-request/169/consoleFull
