### ISSUE TITLE
Uncaught TypeError: a.indexOf is not a function

### ISSUE THREAD

**Issue by maskit** [apache/incubator-pulsar#690]
#### Expected behavior

No errors happen on loading the documentation.

#### Actual behavior

![image](https://user-images.githubusercontent.com/153144/29318466-0ee58b1e-820b-11e7-83e8-ef312ae23771.png)

#### Steps to reproduce

- Access the documentation
http://pulsar.incubator.apache.org/docs/latest/getting-started/LocalCluster/

#### System configuration
**OS**: macOS 10.12
**Browser**: Chrome 60.0.3112.101 (Official Build) (64-bit)

**Comment by sarojrout** [comment]
@maskit I do not think there would be osx or browser issue while accessing the documentation. seems like some issue in the browser. Did you try resetting your browser and try accessing the url again?

**Comment by maskit** [comment]
I didn't reset my browser but I guess it doesn't help. I think it's because of https://github.com/gfranko/jquery.tocify.js/issues/103.

**Comment by maskit** [comment]
This might fix it.
https://github.com/gfranko/jquery.tocify.js/pull/100

Anyway, it seems like jquery.tocify.js isn't maintained. We should probably use some other library instead.

**Comment by advantiot** [comment]
Any recommendations for an equivalent alternative?

**Comment by maskit** [comment]
I'm not familiar with JS libraries. An alternative is proposed.
https://github.com/gfranko/jquery.tocify.js/issues/96

**Comment by advantiot** [comment]
@maskit Actually [gfranko/jquery.tocify.js#100](url) does fix it. More specifically [tomparle/jquery.tocify.js](url)

Thank you and thank you Thomas Parle.

**Comment by sijie** [comment]
The website has been redesigned. so the bug won't be valid anymore.
