### ISSUE TITLE
Introduce retry logic for creating producers and consumers

### ISSUE THREAD

**Issue by jai1** [apache/incubator-pulsar#715]
### Requirement
Creation of Producer / Subscriber can fail due to:-
a. Genuine issues
   - In correct serviceUrl
   - VIP down
   - incorrect topic name etc

b. Intermittent issues
   - Broker Unloading a topic 
   - Broker shutting down
   - Intermittent network issues
   - connection Timeout due to GC pause.

For the (b. Intermittent Issues) the client has no option but to backoff and retry.

I think this is a common enough use case to introduce new APIs (to not break Binary compatibility) for createProducer and subscribe - which will be simple wrappers over the existing APIs. These APIs will take an additional parameter retrycount, they will just blindly retry after backoff. 

@merlimat @rdhabalia @saandrews - Wanted to know your views on this.

**Comment by jai1** [comment]
Edit
Instead of new API we can just add the retry count as a part of client configuration.

**Comment by merlimat** [comment]
Creating producer/consumer has already retry logic for transient errors. The retry is done with exponential backoff delays up to the configured `operationTimeout`, which is by default 30s.

**Comment by jai1** [comment]
To the best of my knowledge - the reconnection logic triggers only once the connection is established atleast once:-
https://github.com/apache/incubator-pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/HandlerBase.java#L113

What I want is that we try to retry even if we are unable to establish the connection the first time due to intermittent failures leading to getPartitionedTopicMetadata to fail. In other words, I want to add a for loop here:- 
https://github.com/apache/incubator-pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java#L159

**Comment by merlimat** [comment]
> To the best of my knowledge - the reconnection logic triggers only once the connection is established atleast once:-

If that's the case it would be a bug :)

It should be easy to have a unit test to show it. Create the producer asynchronously, then bring up the broker within few seconds and verify the producer gets created correctly.

**Comment by sijie** [comment]
@jai1 @merlimat : is this still a bug?

**Comment by pondering-pythagoras** [comment]
Was there an option added for retryCount then?
