### ISSUE TITLE
Avoid huge backlog on topic reloading: due to large gap between markDelete-offset and read-position of cursor.

### ISSUE THREAD

**Issue by rdhabalia** [apache/incubator-pulsar#742]
### Issue
**Avoid huge backlog on topic reloading:** due to large gap between markDelete-offset and read-position of cursor.

Right now, if client missed to ack some of the messages  and keep consuming data then cursor can not advance the markDelete position and readPosition moved far more than markDeletePosition. Now, if that topic gets unloaded and reloaded, cursor recovers readPosition as markDeletePosition and cursor starts delivering messages from markDeletePosition (which was far behind then actual read-position) which suddenly creates a huge back-log and client has to consume duplicate messages.

Therefore, broker should notify to the client if distance between markDelete and readPosition reached to certain threshold. so, later on client will not face backlog and duplicate message delivery issue on topic unloading.

Right now, we do store configured number of unackMsg-range for cursor-recovery but if this range is not enough to prevent this huge-backlog issue then broker should have a mechanism to notify client. 

### Possible solution
In this case, if distance between markDelete and readPosition reached to configured threshold then broker can block subscriber and stop delivering new messages and only deliver unack-messages to subscriber so, subscriber can ack them first which can advance markDelete-position near to cursor's readPosition. Once, markDelete position advanced to expected threshold then broker again unblock subscriber and start delivering new messages.

**Comment by merlimat** [comment]
>Therefore, broker should notify to the client if distance between markDelete and readPosition reached to certain threshold. so, later on client will not face backlog and duplicate message delivery issue on topic unloading.

It's not just the gap. The described problem would only happen if there are many gaps in the acknowledgments, eg. consumer is acking every other message.

>  Once, markDelete position advanced to expected threshold then broker again unblock subscriber and start delivering new messages.

We should already have that mechanism in place, right?

**Comment by rdhabalia** [comment]
> We should already have that mechanism in place, right?

Umm.. we have mechanism to block consumer if number of unack-msg reached to threshold (consumer > 50K and subscription > 4M). 
However, frequently we are seeing issue with client when client has unack-msg < 50K but due to ack-holes, difference between markDelete-position and readPosition gets big (eg: 10M). In this case, when broker restarts, client often sees huge backlog and they consume same 10M messages again. 
We are seeing this behavior often so, we feel there should be a mechanism where broker can notify consumer so, broker restart won't build huge backlog.
I think we can solve this issue by increasing unack-msg range in cursor-metadata but then it can increase metadata footprint as well.
+@saandrews

**Comment by merlimat** [comment]
> is case, when broker restarts, client often sees huge backlog and they consume same 10M messages again.

Again, this should not happen if the number of "holes" is less than the configured max (`managedLedgerMaxUnackedRangesToPersist=1000`). Perhaps that could be increased, given that with binary encoding it should be much more compact.

> We are seeing this behavior often so, we feel there should be a mechanism where broker can notify consumer so, broker restart won't build huge backlog.

I don't see how notifying client library can get the issue fixed. It's most probably application logic problem. I think a better approach would be to have some clear metric that can be used to trigger alert, through monitoring system.

**Comment by rdhabalia** [comment]
> Again, this should not happen if the number of "holes" is less than the configured max `(managedLedgerMaxUnackedRangesToPersist=1000)`.  Perhaps that could be increased

Yes, I have mentioned the same that increasing unackmsg-range in cursor-matadata should solve this issue. But team's only concern was the footprint size which can be increased with it. However, with 1.20-release we will enable it and can close this issue if team is fine with storing reasonable unack-msg range.

**Comment by merlimat** [comment]
> But team's only concern was the footprint size which can be increased with it 

It should be easy to estimate footprint. In any case, we should report the number of these "holes" in the stats, so that we can have alerts on it.

**Comment by rdhabalia** [comment]
Actually, I tried to write a sample test which measures the Text/Binary content size for managed-ledger when we store markDeleteRange in it.
[Test](https://github.com/rdhabalia/pulsar/blob/6dc03356b3c4c42fc3c8bafc8ff85a6de80da574/managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorSizeTest.java)

It basically builds a content in Text/Binary with number of markDeleteRange = [0,10,100]
**Output**
```
Total-markDeleteRange = 0, Text-size = 80, Binary-size= 14, size-multiplier= 5
Total-markDeleteRange = 10, Text-size = 1453, Binary-size= 154, size-multiplier= 9
Total-markDeleteRange = 1000, Text-size = 141339, Binary-size= 15928, size-multiplier= 8
```

- So, Right now, without storing markDeleteRange in **Text** format znode size = 80 bytes. 
- If we store 10 markDeleteRange in **Binary** format then size = 154 bytes
- If we store 1K markDeleteRange in **Binary** format then size = 15Kb

**Comment by merlimat** [comment]
> If we store 1K markDeleteRange in Binary format then size = 15Kb

I believe anything around 150Kb should be fine. Then 10K max range should be a good max size

**Comment by rdhabalia** [comment]
> I believe anything around 150Kb should be fine.

Actually, One of the benefit of moving text to binary format is reducing footprint size. If per cursor-znode (with ack-holes) it increases 80 bytes to 150KB then we may not want to store 10K range to avoid higher footprint size.

Here, with storing 10 range in binary format increases size from 80 bytes to 150 bytes which kind of keeps footprint stable. But then it will not solve the problem which discussed in this issue where large ack-holes can create backlog. So, I think having option to restrict distance between markDelete and readPosition is something useful for broker.

**Comment by merlimat** [comment]
>  where large ack-holes can create backlog 

large *number* of ack-holes

> So, I think having option to restrict distance between markDelete and readPosition is something useful for broker.

It's not related at all with the distance. I think the better metric is indeed the number of "holes"

**Comment by rdhabalia** [comment]
#758 will address this issue. So, will close it.
