### ISSUE TITLE
Message duplication can occur when cursor is reset

### ISSUE THREAD

**Issue by massakam** [apache/incubator-pulsar#749]
When a cursor is reset, duplicate messages are sometimes delivered to different consumers under the following conditions:

- A subscription type is `Failover`.
- Multiple consumers are connecting.

I'm thinking that the following happened, but there is no clear evidence.

1. For example, there are two connected consumers whose name are "alice" and "bob" on a `Failover` subscription (priority is "alice" > "bob").
2. When a cursor of the subscription is reset, both of the consumers will be disconnected once.
3. Assume that "bob" has reconnected first and received messages.
4. If "alice" has reconnected before "bob" has not acknowledged the messages yet, a broker will redeliver the unacked messages to "alice".
5. Consequently, both of the consumers have received the same messages.

**Comment by merlimat** [comment]
This problem also happens in case of rebalancing. Eg:
 * Consumer `b` is connected
 * Consumer `a` connects and becomes the "active" consumer

I think we could have some kind of delay before starting to deliver to the new "active" consumer.
Example: 
 * `b` is active and receiving messages
 * `a` connects
 * Broker stops sending to `b`
 * Acks from `b` are still coming through
 * Wait for some time, eg. 5 or 10 seconds
 * Start delivering to consumer `a`

That should cover most cases of consumer fast reconnections and failovers.

**Comment by massakam** [comment]
@merlimat Thank you for your comment! I agree with you.

**Comment by merlimat** [comment]
@massakam Do you want to pick this up?

**Comment by massakam** [comment]
@merlimat Yes, I'll try it. However, it might be a little late.

**Comment by merlimat** [comment]
no worries, we can target next release
