### ISSUE TITLE
Add provision to send additional information about encryption key

### ISSUE THREAD

**Issue by saandrews** [apache/incubator-pulsar#797]
Currently we send the encryption key name and value in message metadata in order for consumers to retrieve the key to decrypt the AES key. 
      message KeyByteValue {
        required string key = 1;
        required bytes value = 2;
      }

In some cases, additional information is necessary in addition to the name and value to identify and retrieve corresponding key. One example is the version of the key. When the key version changes in the middle of publishing and without explicit information about the version, consumer will not be able to retrieve the corresponding key.

Following options are considered:
1. Add the metadata about key in protobuf
2. Pack the metadata in value itself and use custom protobuf/class serialization to extract this info.

It is better to add it to the proto since it's efficient and making it optional will address cases where metadata is not needed.

Proposed protobuf diff:
-message KeyByteValue {
+message EncryptionKeys {
        required string key = 1;
        required bytes value = 2;
+       optional string metadata = 3;
 }

We also have to change the CryptoKeyReader interface to pass this additional info.

**Comment by rdhabalia** [comment]
In future, if we want to send additional information in metadata then we have to encode multiple properties into metadata-string. So, instead `string metadata`, what if we add  `KeyValue properties` ? I think that can address sending multiple properties in metadata?

**Comment by merlimat** [comment]
I agree to have optional arbitrary options. Regarding the version, is that general enough to have a "version" field?

**Comment by saandrews** [comment]
@rdhabalia The value has to be byte array for efficiency. Instead of creating another type, its better to keep it this way.

@merlimat When application implements metadata, it could contain more than version. One other example could be information about the AES key or if key is managed using kms, it could be the detailed information about the key. So, I thought keeping a generic name "metadata" could address various use cases.

**Comment by rdhabalia** [comment]
> The value has to be byte array for efficiency. Instead of creating another type, its better to keep it this way.

Actually, I was pointing to `metadata` type as `KeyValue(existing string key-value type)`. We don't have to change `value` field and we can keep it as `bytes` only. 
If we introduce field-name as `version` then I think `string` type is enough because we know it will contain only version. But if we want to use it for multiple fields in future then it will be hard to accommodate in one string type. 
So, may be we can call it as `version` right now, and in future introduce `properties` if require?

**Comment by saandrews** [comment]
Thats a good point. We could add it as key/value pair. I'll update the pull request.

**Comment by saandrews** [comment]
Pushed this change as well
