### ISSUE TITLE
Needed bytes type interface in Python client 

### ISSUE THREAD

**Issue by kyontan** [apache/incubator-pulsar#801]
#### Expected behavior

I'm trying to use Pulsar, it's python client and using Protocol Buffers to serialization. 
Python distinctions `bytes` (byte string) and `string` (formally UTF-8 String in Python3).

Protocol Buffers serializes data into *byte string*, so it's result maybe UTF-8 not compliant.
(Python doesn't have method to convert not UTF-8 compliantly `string` to `bytes`.)

I want it to be able to read received message as `bytes`.

#### Actual behavior

I can't deserialize messages sent from another Pulsar client serialized with Protocol Buffers because there's no interface returns `bytes` type of `Message.data()`.

#### Steps to reproduce

(It needed to sent some not UTF-8 compliant messages on the Queue)

```python
import some_message_pb2
import pulsar

client = pulsar.Client('pulsar://localhost:6650')
consumer = client.subscribe(
    'persistent://sample/standalone/ns1/my-topic',
    subscription_name='my-sub')
while True:
    try:
      msg = consumer.receive(timeout_millis=10)
      print("Received")
      # print(msg.data()) # This produces 
      consumer.acknowledge(msg)
client.close()
```

Using IPython: (Interactive shell)
```
In [16]: msg.data();
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-16-xxx> in <module>()
----> 1 msg.data();

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 39-40: invalid continuation byte
```

#### System configuration
**Pulsar version**: 1.19.0-incubating

`pulsar_client-1.19.0`

**Comment by yush1ga** [comment]
Resolved by #812
