### ISSUE TITLE
Global and local zookeeper should use different stats server ports

### ISSUE THREAD

**Issue by ivankelly** [apache/incubator-pulsar#813]
Global and local both try to use port 8080 so they can't be started on the same machine out of the box. -Dstats_server_port will work around the issue.

Note that from zookeeper 3.5.0 onwards, zookeeper itself runs an admin server on 8080.

#### Expected behavior
I expect to be able to start a global zookeeper and local zookeeper node on the same machine

#### Actual behavior
One will fail because they are both trying to bind 8080 for the stats server.

#### Steps to reproduce
Try to set up a cluster with global and local on same node.

#### System configuration
1.20.0-incubating (rc0)

**Comment by ivankelly** [comment]
Moreover, setting this define is a pain. You need to dig into bin/pulsar to figure out the environment variable. I expected it'd be PULSAR_EXTRA_OPTS, but pulsar-env stomps on this. You can't change pulsar-env because global and local both use this. You have to set it in OPTS.

**Comment by awilliams** [comment]
I worked around this by updating `conf/pulsar_env.sh`, changing where `PULSAR_EXTRA_OPTS` is overwritten. I then launch global zookeeper with the following env variable set:

```shell
PULSAR_EXTRA_OPTS="-Dstats_server_port=8081"
```

Modified line ([original](https://github.com/apache/incubator-pulsar/blob/539c8182037fe540433eeb4e7072e4bf2b3eae04/conf/pulsar_env.sh#L51)):

```
PULSAR_EXTRA_OPTS="${PULSAR_EXTRA_OPTS} ${PULSAR_MEM} ${PULSAR_GC} -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024"
```
