### ISSUE TITLE
C++ client is appending partition id to subscription name

### ISSUE THREAD

**Issue by merlimat** [apache/incubator-pulsar#827]
#### Expected behavior

When subscribing to a partitioned topic, a consumer should use the same subscription name on all the partitions. 

This is important because many tools that operate at the partitioned topic level are assuming it. Eg: clear backlog, get partitioned-stats, etc..

#### Actual behavior

Java client is using the correct name, while C++ client (and Python which is built on it as well) is appending the partition id to the subscription name. Eg: `sub0` instead of the user-specified `sub`. 

https://github.com/apache/incubator-pulsar/blob/master/pulsar-client-cpp/lib/PartitionedConsumerImpl.cc#L182

**Comment by merlimat** [comment]
My suggestion is that we should fix this ASAP, before anyone starts using Python client library for consuming from partitioned topics.

@yush1ga @nkurihar @massakam Can you check whether you have any use case depending on this subscription namings?

**Comment by rdhabalia** [comment]
few options to handle clients which are already using existing CPP client lib for partitioned topics which is sending invalid sub-name:

1. Broker rejects requests for the client which are using old cpp-client when it tries to create consumer for partitioned topic

2. In CPP client: while creating consumer: For partitioned-topic: 
**Client change:** 
let client passes the invalid subscription-name (sub-name + index: eg: `my-sub0`) and additional send actual subscription-name (sub-name: eg: `my-sub`). 
**Broker change:**
broker will receive two subs-names, it means it's a partitioned-topic and coming from new cpp-lib. Now, broker will check if new sub-name (`my-sub`) present : if it's not present then broker will create a new cursor with sub-name (`my-sub`)  by copying from provided invalid sub-name (`my-sub0`)  and delete invalid cursor (`my-sub-0`) 

3. New CPP client will pass correct sub-name. But now, broker will find out if this topic is a partitioned-topic ? If it is then is there any old-invalid-cursor present? If yes, then copy from old-invalid to new cursor and delete old-invalid cursor.

**Comment by yush1ga** [comment]
@merlimat 
Our users have not started to use C++ client yet.
Therefore, our users will not be affected by that changing.

**Comment by saandrews** [comment]
Option 3 seems to be better if we can also address cases where old and
newer version of cpp clients are connected to the broker.

**Comment by merlimat** [comment]
> 3. New CPP client will pass correct sub-name. But now, broker will find out if this topic is a partitioned-topic ? If it is then is there any old-invalid-cursor present? If yes, then copy from old-invalid to new cursor and delete old-invalid cursor.

> Option 3 seems to be better if we can also address cases where old and newer version of cpp clients are connected to the broker.

I think it would be trick to pull it right and a bit confusing in any case. 

I'd prefer to just fix the name (since it appears that no one is using C++ partitioned consumers in prod) and do a fix release for this and other bug fixes for 1.20.0

**Comment by saandrews** [comment]
ok with me.

**Comment by rdhabalia** [comment]
> I'd prefer to just fix the name

But then what if someone uses old client version and then upgrade to new client version? client will lose the data. So, it's better to add some handling so, client won't lose the data. 

yes, option-2/3 will be tricky for broker to figure out partitioned-topic. 
because in these options new cpp-client sends legacy sub-name (sub-name + partitioned-index) so, broker can copy old cursor to new cursor and delete old one. But if someone is still using old client then there will be conflict and it will be tricky to find out if it's genuine or legacy sub-name.

Then should we add at least add option-1 where we won't allow client to connect with old cpp-client version if client wants to use partitioned-topic (partitioned-metadata-lookup)?

**Comment by merlimat** [comment]
> Then should we add at least add option-1 where we won't allow client to connect with old cpp-client version if client wants to use partitioned-topic (partitioned-metadata-lookup)?

> Broker rejects requests for the client which are using old cpp-client when it tries to create consumer for partitioned topic

But the problem is not upgrading the broker, rather upgrading the client. I don't see how this could help here.

**Comment by rdhabalia** [comment]
> But the problem is not upgrading the broker, rather upgrading the client.

we have already published cpp-client lib with old versions and they are being used by clients for non-partitioned topics right now. But there is no guarantee that client will not use old-client library for partitioned topics. 
So, even if we introduce new cpp-version and if first client uses old version and then upgrade to new version then it will create two separate cursors which will cause the data lose. 

> I don't see how this could help here.

So, if broker rejects old-cpp client request for for partitioned-topic-subscription then client won't be able to use old cpp-client and they have to upgrade to new version if client wants to subscribe on partitioned-topic. So, it can prevent client to use old-cpp version.

**Comment by merlimat** [comment]
Good point, we can certainly do that

**Comment by merlimat** [comment]
This was fixed in 1.21 release
