### ISSUE TITLE
Allow selective roles to go through pulsar proxy

### ISSUE THREAD

**Issue by jai1** [apache/incubator-pulsar#858]
Currently, any property can connect to the proxy, we want to restrict the access to selective properties only. 

A simple solution would be to add a static parameter _allowesRoles_ in the configuration file and after initial authentication (during connect) do a mini authorization to check if the role exists in the _allowesRoles_ params. 

Alternately we can create a ZK node for dynamic configuration.

@merlimat @rdhabalia @saandrews  - Do you think this is a good approach??

**Comment by merlimat** [comment]
What about restricting which namespaces the proxy can use?

**Comment by jai1** [comment]
Are you suggesting to have a list of allowed namespaces (in zk or config file)?

In production, roles are closely mapped to a namespace - though not necessarily

**Comment by rdhabalia** [comment]
> What about restricting which namespaces the proxy can use?

I think here idea is to make proxy available for specific tenants and each tenant can have many namespaces. So, if we add restriction on namespace bases then it will require to configure many/all namespaces for that tenant. 
So, probably if proxy can authorized based on tenant-role then only certain tenants will only pass through proxy which may save admin-efforts to configure each namespace of that tenant?

**Comment by jai1** [comment]
We can configure both mechanisms and let the user choose which one to use. Will create a PR soon for this.

**Comment by merlimat** [comment]
what about adding another permission category, `proxy`, in addition to `produce` and `consume`?

**Comment by merlimat** [comment]
I don't really like having to put all the roles in the proxy configuration. If we can leverage the existing tools to update the permissions, it would be better

**Comment by jai1** [comment]
> I don't really like having to put all the roles in the proxy configuration. If we can leverage the existing tools to update the permissions, it would be better

Agreed

We are still contemplating on how and where to deploy the proxy

There are two problems that we want to address:-
1. *Restricting a particular proxy machines access to certain namespaces only:*
As suggested by @merlimat we can add a proxies role to auth_policies - namespace_auth and broker authorizes the proxy role (extracted from proxies certificate).
 
2. *Proxy impersonating any client - by extracting and sending the originalAppID*
As suggested by @msb-at-yahoo we forward the client certificate data (Athens token) along with the Proxy certificate data to the broker and the broker authenticates both, extracts the client's role and authorizes it.

**Comment by merlimat** [comment]
> 2. Proxy impersonating any client - by extracting and sending the originalAppID

That's exactly how it works right now. 

> orward the client certificate data (Athens token) along with the Proxy certificate data to the broker and the broker authenticates both, extracts the client's role and authorizes it. 

If I can use the token from the client, wouldn't that mean that by intercepting the TCP traffic I can impersonate a specific client with Athens? 

In any case that won't work in many auth schemes (eg: TLS).

**Comment by jai1** [comment]
> That's exactly how it works right now.

Yes and we are debating if this is a correct thing to do

> If I can use the token from the client, wouldn't that mean that by intercepting the TCP traffic I can impersonate a specific client with Athens?

Yes, but the impersonation will be a bit more difficult since now need a valid client certificate with an authorizable role to impersonate the client.

> In any case that won't work in many auth schemes (eg: TLS).

Agreed, it will not work for all schemes - will work only for Athens, which is not good from open source point of view. 

=========
As I said, we are still evaluating all the approaches to make the proxy more secure. We will also have an internal meeting with the security team to discuss what is the most secure approach.

**Comment by merlimat** [comment]
@jai1 This was already done, right? Can we close the issue?
