### ISSUE TITLE
Avoid confliction of subscription names for multiple tenants

### ISSUE THREAD

**Issue by yush1ga** [apache/incubator-pulsar#893]
A topic of Pulsar can be used by multiple tenants.
They have to be careful not to make a subscription name conflict.

I propose `subscription_auth_mode` for namespace policies.

### 0. None
as before

### 1. Subscription Prefix
When `subscription_auth_mode` in a namespace policy is `Prefix` and `AuthenticationEnabled` in `broker.conf` is `true`, a client have to use subscription name including role name prefix like `${AuthRroleName}-foobar`.

### 2. Reserved subscription name
When `subscription_auth_mode`  is `Reservation`, refer to `subscription_auth` in AuthPolicies like following.
```
subscription_auth: {
    sub1: [role1],
    sub23: [role2, role3]
}
```
In this case, `sub1` can be used by only `role1` and `sub23` can be used by only `role2`and `role3`.

**Comment by sijie** [comment]
This is fixed by #899
