### ISSUE TITLE
Allow running bookie together with broker

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#922]
Description:

To simplify deployment, it will be good to run bookie along with broker. so people don't have to run separate bookkeeper cluster. It is good for small-size or midsize deployments.

**Comment by merlimat** [comment]
👍  We could add a config option on whether to start bookie component in same process as broker, also with bookie auto-recovery as well. 

In any case, we should just point the bookie to `conf/bookkeeper.conf` without having to import the same config keys into `broker.conf`

**Comment by joefk** [comment]
And ZK too. For small prod deployments,(eg: 2 broker, 3 BK system), running 5 ZK servers is too much.

**Comment by zhaijack** [comment]
@joefk  would like to handle bookies in this issue this time, since zk seems easier to deploy and config, If needed, we could do it later.
#961 is for this issue.

**Comment by merlimat** [comment]
>And ZK too. For small prod deployments,(eg: 2 broker, 3 BK system), running 5 ZK servers is too much. 

@joefk Main problem with ZK is that we have to provide list of hosts. 
It's a bit involved, but it could work if we do something like : 

`bin/pulsar broker --brokers-list brk-1,brk-2,brk-3` 

on each of the 3 nodes, to make sure they can form a quorum. It's more involved than starting the bookie though. And it's already possible to start the ZK process separately in the same nodes.
