### ISSUE TITLE
PIP-9: Topic Compaction

### ISSUE THREAD

**Issue by ivankelly** [apache/incubator-pulsar#933]
Top level issue for pulsar topic compaction. 

To read the proposal see: https://github.com/ivankelly/incubator-pulsar-wiki/blob/pip-9/PIP-9:-Topic-Compaction.md
To review: https://github.com/ivankelly/incubator-pulsar-wiki/pull/1

(unfortunately github doesn't allow PRs on wikis, but once we have a final draft of the proposal, a committer can apply the patch and push)

**Comment by ivankelly** [comment]
@merlimat who would be best to review this, so I can assign it?

**Comment by sijie** [comment]
@ivankelly I think the proposal workflow is not github based. Can you send an email to dev@ list to start a discussion thread for that?

**Comment by ivankelly** [comment]
Sure. Will send an email. I put it on github so I can easily collect comments

**Comment by mgodave** [comment]
Looks good.

Regarding your open question:

> Should the compactor have a subscription so that it can cause messages to be retained until compaction occurs.

If I'm reading this correctly, you will need to make sure the topic is still around so you will indeed require a cursor. On the first pass through you can read without acknowledgement and save acknowledgement until the second pass. This would also prevent a compact job that crashes anytime between the start and finish from missing data.

**Comment by sijie** [comment]
Here are some notes about the discussion between @ivankelly @merlimat @mgodave and me:

- regarding "message deletion": it is okay either to use `empty content` as the delete message or use an explicit flag in message header to indicate that the message is a deletion message

- regarding client behavior reacting to `compacted data`
  * existing subscriptions (existing applications) should still read the `raw data` even the topic is configured to be a compacted topic
  * reading `compacted data` from a compacted topic should be explicitly called by a client through a flag or calling seek to earliest message of `compacted data`.
  * while reading `compacted data`, if a consumer/reader falls behind, by default it should just falls behind. fast-forward to new compacted data should be explicitly specified/configured in the consumer configuration.

@ivankelly @merlimat @mgodave - please take a look at these notes. let me know if I missed anything.

**Comment by ivankelly** [comment]
@mgodave The real question here is whether it matters if messages go away between the runs. If the messages go away, the client of the backlog wouldn't be able to read them anyhow, so why would they need to read them from the compacted topic.

**Comment by ivankelly** [comment]
Updated the PR

**Comment by merlimat** [comment]
Done
