### ISSUE TITLE
Upgrade Jackson version to latest patch (or later minor version)

### ISSUE THREAD

**Issue by cowtowncoder** [apache/incubator-pulsar#941]
This is more of a minor request for maintenance, not bug per se, but I noticed that the project has a dependency to rather old patch version of Jackson, `2.4.3`.
Since newer versions typically contain many bug fixes, I would suggest dependency upgrade.
The safest option would be simply to use latest 2.4 patch, `2.4.6`:

http://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

but it might make sense to consider an upgrade to a later minor version as well.
This could help with transitive dependencies as well since most frameworks these days rely on Jackson `2.8`, `2.8.9` being the most "popular" patch version (and `2.8.10` latest)

**Comment by merlimat** [comment]
Thanks for pointing out @cowtowncoder, coming from Jackson maintainer, we'll take the advice seriously! :)

**Comment by cowtowncoder** [comment]
@merlimat No prob -- let me know if I can help. I have some vested interest here too, many co-workers are actually evaluating use of Pulsar, lots of excitement. So really wishing all the best with development, hoping to learn more myself.
