### ISSUE TITLE
Compacted message serialization and deserialization

### ISSUE THREAD

**Issue by ivankelly** [apache/incubator-pulsar#965]
For compaction, we want to store the the message ID, metadata and payload for each retained message. 
The payload is currently stored along with the metadata inside a ledger entry. The message ID is generated from the ledger id and entry id.
We want the compacted messages to have the same ID as before they were compacted. This means we need to also store the message ID in the ledger entry.

We need serialization and deserialization methods for this (see Commands.java)

**Comment by ivankelly** [comment]
#1039

**Comment by merlimat** [comment]
done
