### ISSUE TITLE
Bug: Download page must include KEYS, sig and hashes

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-pulsar#986]
The download page https://pulsar.incubator.apache.org/download/ has links to the source and binary archives on the 3rd party mirrors. However it also needs links to the KEYS, sig and hashes.

See:
http://www.apache.org/dev/release-distribution#sigs-and-sums

**Comment by sijie** [comment]
fyi, @lucperkins is working on this.

**Comment by sijie** [comment]
@sebbASF : @lucperkins put up a pull request to add sigs, hashes and KEYS to pulsar downloads page. can you also help review his change?

**Comment by merlimat** [comment]
@sebbASF We have added the links for the keys in the download page. Please check whether it's correct now. https://pulsar.incubator.apache.org/download/

**Comment by sebbASF** [comment]
Sorry but the page is still incorrect.

KEYS, sigs and hashes must be linked from www.apache.org/dist/... and should use https.

Do not use the archive site (except for old releases that are no longer current)

The dist.apache.org host should never be used for public downloads.
It is only intended for use by developers during release voting and staging.

The "Other releases" section needs to make it clear that these are older releases.
Also there should be sigs and hashes for these. 
The current release KEYS file link (i.e. https://www.apache.org/dist/incubator/pulsar/KEYS) can also be used for past releases as RM keys should not be dropped, only added.

**Comment by merlimat** [comment]
@sebbASF Thanks for feedback, we'll incorporate ASAP

**Comment by merlimat** [comment]
@sebbASF the page was updated a couple of weeks back, can you give it another look? Thanks

**Comment by sebbASF** [comment]
As I wrote previously:

"KEYS, sigs and hashes must be linked from www.apache.org/dist/... and should use https."

Only KEYS currently links to www.apache.org/dist/incubator/pulsar and it does not use https.
The links to the sigs and hashes currently don't work at all as such files are not mirrored.

The older releases section links to the correct host. However the hashes and sigs should use https.

The page should also mention the need to check releases against the sig or failing that a hash.
For example, see how Tomcat does it:

https://tomcat.apache.org/download-90.cgi#Release_Integrity

**Comment by merlimat** [comment]
@sebbASF I think that finally I should have captured all the points. Thanks for explaining multiple times!

**Comment by sebbASF** [comment]
Thanks, it looks as though you have fixed all the points I raised
