### ISSUE TITLE
Maven artifacts missing for Pulsar 1.21-incubating

### ISSUE THREAD

**Issue by sschepens** [apache/incubator-pulsar#991]
Artifacts for newest release 1.21-incubating are missing in mavencentral: https://mvnrepository.com/artifact/org.apache.pulsar/pulsar-client

**Comment by merlimat** [comment]
I failed to add the last step in the "Release process" wiki. 

I've just promoted the last RC artifacts to be released in the ASF nexus repository. In a few hours they will be available on Maven central. 

I have updated the wiki to include the step in the release process.

**Comment by merlimat** [comment]
Artifacts are synced in Maven central now: https://search.maven.org/#artifactdetails%7Corg.apache.pulsar%7Cpulsar-client%7C1.21.0-incubating%7Cjar

**Comment by nkurihar** [comment]
@merlimat 
Thanks!
I'm sorry for forgetting to deploy to maven central.
